package com.nemonicworld.fortune.controller;

import static org.hamcrest.Matchers.nullValue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.nemonicworld.common.header.AnonymousUserHeaders;
import com.nemonicworld.fortune.service.gms.FortuneGmsClient;
import com.nemonicworld.fortune.service.gms.FortuneGmsResult;
import com.nemonicworld.fortune.service.image.FortuneCardStorage;
import com.nemonicworld.support.IntegrationTest;
import com.nemonicworld.user.entity.AppUser;
import com.nemonicworld.user.repository.UserRepository;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.http.MediaType;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=create-drop")
/**
 * 오늘의 운세 생성 가능 여부 조회 API를 통합 검증합니다.
 */
class FortuneControllerIntegrationTest {

    private static final String ANONYMOUS_USER_UUID_HEADER = AnonymousUserHeaders.ANONYMOUS_USER_UUID;
    private static final ZoneId KST_ZONE = ZoneId.of("Asia/Seoul");

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private UserRepository userRepository;

    @MockitoBean
    private FortuneGmsClient fortuneGmsClient;

    @MockitoBean
    private FortuneCardStorage fortuneCardStorage;

    @BeforeEach
    void prepareFortuneTables() {
        reset(fortuneGmsClient, fortuneCardStorage);
        jdbcTemplate.execute("DROP TABLE IF EXISTS fortune_artifact");
        jdbcTemplate.execute("DROP TABLE IF EXISTS gallery");
        jdbcTemplate.execute("DROP TABLE IF EXISTS artifact");
        jdbcTemplate.execute("DROP TABLE IF EXISTS gms_prompt_template");
        jdbcTemplate.execute("""
            CREATE TABLE artifact (
                id UUID PRIMARY KEY,
                kind VARCHAR(32) NOT NULL,
                source_room_id VARCHAR(64) NULL,
                thumbnail_url VARCHAR(200) NOT NULL,
                meta VARCHAR(1000) NOT NULL DEFAULT '{}',
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE fortune_artifact (
                artifact_id UUID PRIMARY KEY,
                description VARCHAR(1000) NOT NULL,
                fortune_image_url VARCHAR(200) NOT NULL,
                user_id UUID NOT NULL,
                fortune_date DATE NOT NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE UNIQUE INDEX uq_fortune_artifact_user_date
            ON fortune_artifact (user_id, fortune_date)
            """);
        jdbcTemplate.execute("""
            CREATE TABLE gallery (
                id UUID PRIMARY KEY,
                user_id UUID NOT NULL,
                artifact_id UUID NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE gms_prompt_template (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                prompt_name VARCHAR(64) NOT NULL,
                template_text VARCHAR(2000) NOT NULL,
                feature_type VARCHAR(32) NOT NULL,
                created_by BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
    }

    /**
     * 만세력 결과로 운세를 생성하면 artifact, fortune_artifact, gallery가 함께 저장됩니다.
     */
    @Test
    void createFortuneCreatesArtifactAndGallery() throws Exception {
        UUID userUuid = createExistingUser();
        insertPrompt();
        when(fortuneGmsClient.generate(anyString(), any(JsonNode.class))).thenReturn(sampleGmsResult());

        mockMvc
            .perform(post("/api/v1/fortune").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString())
                .contentType(MediaType.APPLICATION_JSON).content(sajuRequestBody()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("오늘의 운세 생성 성공")).andExpect(jsonPath("$.data.fortuneId").isNotEmpty())
            .andExpect(jsonPath("$.data.date").value(LocalDate.now(KST_ZONE).toString()))
            .andExpect(jsonPath("$.data.title").value("오늘은 흐름을 정리하는 날"))
            .andExpect(jsonPath("$.data.summary").value("차분하게 우선순위를 세우면 좋은 결과가 나는 하루입니다."))
            .andExpect(jsonPath("$.data.overallLuck").value(78)).andExpect(jsonPath("$.data.loveLuck").value(66))
            .andExpect(jsonPath("$.data.workLuck").value(84)).andExpect(jsonPath("$.data.moneyLuck").value(71))
            .andExpect(jsonPath("$.data.luckyColor").value("은회색"))
            .andExpect(jsonPath("$.data.luckyKeyword").value("정리"))
            .andExpect(jsonPath("$.data.caution").value("결정은 한 템포 늦추는 것이 좋습니다."))
            .andExpect(jsonPath("$.data.postitLine").value("오늘은 정리할수록 운이 열린다"));

        String savedDescription = jdbcTemplate
            .queryForObject("SELECT description FROM fortune_artifact WHERE user_id = ?", String.class, userUuid);
        Integer artifactCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM artifact WHERE kind = 'fortune'",
            Integer.class);
        Integer galleryCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM gallery WHERE user_id = ?",
            Integer.class, userUuid);

        org.assertj.core.api.Assertions.assertThat(artifactCount).isEqualTo(1);
        org.assertj.core.api.Assertions.assertThat(galleryCount).isEqualTo(1);
        org.assertj.core.api.Assertions.assertThat(savedDescription).contains("\"title\":\"오늘은 흐름을 정리하는 날\"")
            .contains("\"yearPillar\":\"임신\"");
        verify(fortuneCardStorage).upload(org.mockito.ArgumentMatchers.startsWith("fortune/cards/"), any(byte[].class),
            eq("image/png"));
    }

    /**
     * 같은 UUID가 같은 KST 날짜에 다시 생성하면 GMS 호출 전 409로 차단합니다.
     */
    @Test
    void createFortuneReturnsConflictWhenUserAlreadyCreatedToday() throws Exception {
        UUID userUuid = createExistingUser();
        insertFortuneArtifact(userUuid, LocalDate.now(KST_ZONE), LocalDateTime.now().minusMinutes(10));

        mockMvc
            .perform(post("/api/v1/fortune").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString())
                .contentType(MediaType.APPLICATION_JSON).content(sajuRequestBody()))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("오늘의 운세는 이미 생성했습니다. 내일 다시 이용해주세요."));

        verifyNoInteractions(fortuneGmsClient, fortuneCardStorage);
    }

    /**
     * 만세력 필수 필드가 없으면 GMS 호출 전 400으로 차단합니다.
     */
    @Test
    void createFortuneReturnsBadRequestWhenSajuIsInvalid() throws Exception {
        UUID userUuid = createExistingUser();

        mockMvc
            .perform(post("/api/v1/fortune").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "calendarType": "solar",
                      "yearPillar": "임신"
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("만세력 결과 정보가 올바르지 않습니다."));

        verifyNoInteractions(fortuneGmsClient, fortuneCardStorage);
    }

    /**
     * GMS 생성이 최종 실패하면 DB 저장 없이 503을 반환합니다.
     */
    @Test
    void createFortuneDoesNotConsumeDailyLimitWhenGmsFails() throws Exception {
        UUID userUuid = createExistingUser();
        insertPrompt();
        when(fortuneGmsClient.generate(anyString(), any(JsonNode.class))).thenThrow(new RuntimeException("gms down"));

        mockMvc
            .perform(post("/api/v1/fortune").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString())
                .contentType(MediaType.APPLICATION_JSON).content(sajuRequestBody()))
            .andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("운세를 가져오지 못했어요. 잠시 후 다시 시도해 주세요."));

        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM fortune_artifact", Integer.class);
        org.assertj.core.api.Assertions.assertThat(count).isZero();
        verify(fortuneGmsClient, times(3)).generate(anyString(), any(JsonNode.class));
        verifyNoInteractions(fortuneCardStorage);
    }

    /**
     * 오늘 생성된 운세가 없으면 생성 가능 상태를 반환합니다.
     */
    @Test
    void getTodayAvailabilityReturnsAvailableWhenUserHasNoFortuneToday() throws Exception {
        UUID userUuid = createExistingUser();
        LocalDate today = LocalDate.now(KST_ZONE);

        mockMvc
            .perform(get("/api/v1/fortune/today/availability").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("오늘의 운세 생성 가능 여부 조회 성공"))
            .andExpect(jsonPath("$.data.available").value(true))
            .andExpect(jsonPath("$.data.fortuneDate").value(today.toString()))
            .andExpect(jsonPath("$.data.todayFortuneId").value(nullValue()))
            .andExpect(jsonPath("$.data.createdAt").value(nullValue()))
            .andExpect(jsonPath("$.data.nextAvailableAt").value(nextAvailableAt(today)));
    }

    /**
     * 오늘 생성된 운세가 있으면 재생성 불가와 기존 fortuneId를 반환합니다.
     */
    @Test
    void getTodayAvailabilityReturnsUnavailableWhenUserAlreadyHasFortuneToday() throws Exception {
        UUID userUuid = createExistingUser();
        LocalDate today = LocalDate.now(KST_ZONE);
        LocalDateTime createdAt = LocalDateTime.now().minusMinutes(10).truncatedTo(ChronoUnit.SECONDS);
        UUID fortuneId = insertFortuneArtifact(userUuid, today, createdAt);

        mockMvc
            .perform(get("/api/v1/fortune/today/availability").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.available").value(false))
            .andExpect(jsonPath("$.data.fortuneDate").value(today.toString()))
            .andExpect(jsonPath("$.data.todayFortuneId").value(fortuneId.toString()))
            .andExpect(jsonPath("$.data.createdAt").value(createdAt.toString()))
            .andExpect(jsonPath("$.data.nextAvailableAt").value(nextAvailableAt(today)));
    }

    /**
     * 다른 사용자가 오늘 운세를 생성했더라도 현재 사용자의 생성 가능 여부에는 영향을 주지 않습니다.
     */
    @Test
    void getTodayAvailabilityIgnoresOtherUsersFortune() throws Exception {
        UUID userUuid = createExistingUser();
        UUID otherUserUuid = createExistingUser();
        LocalDate today = LocalDate.now(KST_ZONE);

        insertFortuneArtifact(otherUserUuid, today, LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/fortune/today/availability").header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.available").value(true))
            .andExpect(jsonPath("$.data.todayFortuneId").value(nullValue()));
    }

    /**
     * UUID 헤더가 없거나 형식이 올바르지 않으면 400을 반환합니다.
     */
    @Test
    void getTodayAvailabilityReturnsBadRequestWhenUuidIsInvalid() throws Exception {
        mockMvc.perform(get("/api/v1/fortune/today/availability")).andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("유효하지 않은 UUID 형식입니다."));

        mockMvc.perform(get("/api/v1/fortune/today/availability").header(ANONYMOUS_USER_UUID_HEADER, "not-a-uuid"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("유효하지 않은 UUID 형식입니다."));
    }

    /**
     * UUID 형식은 맞지만 서버에 존재하지 않는 사용자이면 404를 반환합니다.
     */
    @Test
    void getTodayAvailabilityReturnsNotFoundWhenUserDoesNotExist() throws Exception {
        mockMvc
            .perform(get("/api/v1/fortune/today/availability").header(ANONYMOUS_USER_UUID_HEADER,
                UUID.randomUUID().toString()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("존재하지 않는 사용자입니다."));
    }

    private UUID createExistingUser() {
        UUID userUuid = UUID.randomUUID();
        LocalDateTime createdAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);

        userRepository.saveAndFlush(AppUser.createAnonymous(userUuid, "MangoApp/1.0", createdAt));

        return userUuid;
    }

    private UUID insertFortuneArtifact(UUID userUuid, LocalDate fortuneDate, LocalDateTime createdAt) {
        UUID fortuneId = UUID.randomUUID();

        jdbcTemplate.update("""
            INSERT INTO artifact (id, kind, source_room_id, thumbnail_url, meta, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """, fortuneId, "fortune", null, "fortune/thumb.png", "{}", Timestamp.valueOf(createdAt),
            Timestamp.valueOf(createdAt));
        jdbcTemplate.update("""
            INSERT INTO fortune_artifact (
                artifact_id, description, fortune_image_url, user_id, fortune_date
            )
            VALUES (?, ?, ?, ?, ?)
            """, fortuneId, "{}", "fortune/card.png", userUuid, fortuneDate);

        return fortuneId;
    }

    private void insertPrompt() {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO gms_prompt_template (
                prompt_name, template_text, feature_type, created_by, created_at, updated_at, deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL)
            """, "Daily fortune", "오늘의 운세를 JSON으로 생성해줘.", "fortune", 1L, Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private FortuneGmsResult sampleGmsResult() {
        return new FortuneGmsResult("오늘은 흐름을 정리하는 날", "차분하게 우선순위를 세우면 좋은 결과가 나는 하루입니다.", 78, 66, 84, 71, "은회색", "정리",
            "결정은 한 템포 늦추는 것이 좋습니다.", "오늘은 정리할수록 운이 열린다", "moon", "#2C2C4A", "#C0C0C0", "moon_waning");
    }

    private String sajuRequestBody() {
        return """
            {
              "calendarType": "solar",
              "yearPillar": "임신",
              "monthPillar": "경술",
              "dayPillar": "계유",
              "hourPillar": "을묘",
              "dayMasterElement": "수",
              "dayBranchElement": "금",
              "dayMasterYinYang": "음",
              "dayBranchYinYang": "음"
            }
            """;
    }

    private String nextAvailableAt(LocalDate today) {
        return today.plusDays(1).atStartOfDay(KST_ZONE).toOffsetDateTime()
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssxxx"));
    }
}
