package com.nemonicworld.gms.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
class GmsPromptControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "prompt-admin";
    private static final String ADMIN_NICKNAME = "Prompt Admin";
    private static final String ADMIN_EMAIL = "prompt-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS gms_prompt_template (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                prompt_name VARCHAR(64) NOT NULL UNIQUE,
                template_text TEXT NOT NULL,
                feature_type VARCHAR(32) NOT NULL,
                created_by BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM gms_prompt_template");
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        jdbcTemplate.execute("ALTER TABLE gms_prompt_template ALTER COLUMN id RESTART WITH 100");
        insertAdminUser();
    }

    @Test
    void adminCreatesPrompt() throws Exception {
        mockMvc
            .perform(post("/api/v1/backoffice/gms/prompts").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content(createRequestBody("Daily fortune")))
            .andExpect(status().isCreated()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.name").value("Daily fortune"))
            .andExpect(jsonPath("$.data.content").value("Prompt body for {{nickname}}."))
            .andExpect(jsonPath("$.data.featureType").value("fortune"))
            .andExpect(jsonPath("$.data.createdBy").value(ADMIN_ID));

        assertThat(countPromptsByName("Daily fortune")).isEqualTo(1);
        assertThat(countPromptsByFeatureType("fortune")).isEqualTo(1);
    }

    @Test
    void adminPromptCreationRejectsDuplicatedName() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(post("/api/v1/backoffice/gms/prompts").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content(createRequestBody("Daily fortune")))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminGetsPromptDetail() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(get("/api/v1/backoffice/gms/prompts/{promptId}", 10L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.id").value(10L)).andExpect(jsonPath("$.data.name").value("Daily fortune"))
            .andExpect(jsonPath("$.data.content").value("Prompt body for {{nickname}}."))
            .andExpect(jsonPath("$.data.featureType").value("fortune"))
            .andExpect(jsonPath("$.data.createdBy").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.createdAt").isNotEmpty()).andExpect(jsonPath("$.data.updatedAt").isNotEmpty());
    }

    @Test
    void adminPromptDetailRejectsUnknownId() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/gms/prompts/{promptId}", 999L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminPromptDetailRejectsAlreadyDeletedPrompt() throws Exception {
        LocalDateTime deletedAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        insertPrompt(10L, "Daily fortune", "fortune", deletedAt);

        mockMvc
            .perform(get("/api/v1/backoffice/gms/prompts/{promptId}", 10L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminPromptDetailRejectsUnauthenticatedRequest() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc.perform(get("/api/v1/backoffice/gms/prompts/{promptId}", 10L)).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminDeletesPrompt() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(delete("/api/v1/backoffice/gms/prompts/{promptId}", 10L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(countPromptsByName("Daily fortune")).isEqualTo(1);
        assertThat(countActivePromptsById(10L)).isZero();
        assertThat(findPromptDeletedAt(10L)).isNotNull();
    }

    @Test
    void adminPromptDeletionRejectsUnknownId() throws Exception {
        mockMvc
            .perform(delete("/api/v1/backoffice/gms/prompts/{promptId}", 999L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminPromptDeletionRejectsAlreadyDeletedPrompt() throws Exception {
        LocalDateTime deletedAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        insertPrompt(10L, "Daily fortune", "fortune", deletedAt);

        mockMvc
            .perform(delete("/api/v1/backoffice/gms/prompts/{promptId}", 10L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findPromptDeletedAt(10L)).isEqualTo(deletedAt);
    }

    @Test
    void adminUpdatesPrompt() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);
        LocalDateTime beforeUpdatedAt = findPromptUpdatedAt(10L);

        mockMvc
            .perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {
                      "name": "Updated fortune",
                      "content": "Updated prompt body.",
                      "featureType": "sticker"
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.id").value(10L)).andExpect(jsonPath("$.data.name").value("Updated fortune"))
            .andExpect(jsonPath("$.data.content").value("Updated prompt body."))
            .andExpect(jsonPath("$.data.featureType").value("sticker"));

        assertThat(findPromptName(10L)).isEqualTo("Updated fortune");
        assertThat(findPromptContent(10L)).isEqualTo("Updated prompt body.");
        assertThat(findPromptFeatureType(10L)).isEqualTo("sticker");
        assertThat(findPromptUpdatedAt(10L)).isAfter(beforeUpdatedAt);
    }

    @Test
    void adminUpdatesPromptNameOnly() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {
                      "name": "Renamed fortune"
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.name").value("Renamed fortune"))
            .andExpect(jsonPath("$.data.content").value("Prompt body for {{nickname}}."))
            .andExpect(jsonPath("$.data.featureType").value("fortune"));
    }

    @Test
    void adminUpdatesPromptContentOnly() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {
                      "content": "Content only update."
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.name").value("Daily fortune"))
            .andExpect(jsonPath("$.data.content").value("Content only update."))
            .andExpect(jsonPath("$.data.featureType").value("fortune"));
    }

    @Test
    void adminUpdatesPromptFeatureTypeOnly() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {
                      "featureType": "sticker"
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.name").value("Daily fortune"))
            .andExpect(jsonPath("$.data.content").value("Prompt body for {{nickname}}."))
            .andExpect(jsonPath("$.data.featureType").value("sticker"));
    }

    @Test
    void adminPromptUpdateRejectsUnknownId() throws Exception {
        mockMvc.perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 999L)
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "name": "Updated fortune"
                }
                """)).andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminPromptUpdateRejectsAlreadyDeletedPrompt() throws Exception {
        LocalDateTime deletedAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        insertPrompt(10L, "Daily fortune", "fortune", deletedAt);

        mockMvc.perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "name": "Updated fortune"
                }
                """)).andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findPromptName(10L)).isEqualTo("Daily fortune");
        assertThat(findPromptDeletedAt(10L)).isEqualTo(deletedAt);
    }

    @Test
    void adminPromptUpdateRejectsEmptyBody() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc
            .perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminPromptUpdateRejectsDuplicatedName() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);
        insertPrompt(11L, "Sticker prompt", "sticker", null);

        mockMvc.perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "name": "Sticker prompt"
                }
                """)).andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findPromptName(10L)).isEqualTo("Daily fortune");
    }

    @Test
    void adminPromptUpdateAllowsOwnName() throws Exception {
        insertPrompt(10L, "Daily fortune", "fortune", null);

        mockMvc.perform(patch("/api/v1/backoffice/gms/prompts/{promptId}", 10L)
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "name": "Daily fortune"
                }
                """)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.name").value("Daily fortune"));

        assertThat(countPromptsByName("Daily fortune")).isEqualTo(1);
    }

    private void insertAdminUser() {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, ADMIN_ID, ADMIN_LOGIN_ID, "encoded", ADMIN_NICKNAME, ADMIN_EMAIL, "admin", Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private void insertPrompt(long id, String name, String featureType, LocalDateTime deletedAt) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO gms_prompt_template (
                id,
                prompt_name,
                template_text,
                feature_type,
                created_by,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, id, name, "Prompt body for {{nickname}}.", featureType, ADMIN_ID, Timestamp.valueOf(now),
            Timestamp.valueOf(now), deletedAt == null ? null : Timestamp.valueOf(deletedAt));
    }

    private String createRequestBody(String name) {
        return """
            {
              "name": "%s",
              "content": "Prompt body for {{nickname}}.",
              "featureType": "fortune"
            }
            """.formatted(name);
    }

    private String bearerAccessToken() {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(ADMIN_ID, ADMIN_LOGIN_ID, "encoded", ADMIN_NICKNAME, ADMIN_EMAIL,
            AdminRole.ADMIN, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private int countPromptsByName(String name) {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM gms_prompt_template WHERE prompt_name = ?",
            Integer.class, name);

        return count == null ? 0 : count;
    }

    private int countActivePromptsById(long id) {
        Integer count = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM gms_prompt_template WHERE id = ? AND deleted_at IS NULL", Integer.class, id);

        return count == null ? 0 : count;
    }

    private LocalDateTime findPromptDeletedAt(long id) {
        Timestamp deletedAt = jdbcTemplate.queryForObject("SELECT deleted_at FROM gms_prompt_template WHERE id = ?",
            Timestamp.class, id);

        return deletedAt == null ? null : deletedAt.toLocalDateTime();
    }

    private LocalDateTime findPromptUpdatedAt(long id) {
        Timestamp updatedAt = jdbcTemplate.queryForObject("SELECT updated_at FROM gms_prompt_template WHERE id = ?",
            Timestamp.class, id);

        return updatedAt == null ? null : updatedAt.toLocalDateTime();
    }

    private String findPromptName(long id) {
        return jdbcTemplate.queryForObject("SELECT prompt_name FROM gms_prompt_template WHERE id = ?", String.class,
            id);
    }

    private String findPromptContent(long id) {
        return jdbcTemplate.queryForObject("SELECT template_text FROM gms_prompt_template WHERE id = ?", String.class,
            id);
    }

    private String findPromptFeatureType(long id) {
        return jdbcTemplate.queryForObject("SELECT feature_type FROM gms_prompt_template WHERE id = ?", String.class,
            id);
    }

    private int countPromptsByFeatureType(String featureType) {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM gms_prompt_template WHERE feature_type = ?",
            Integer.class, featureType);

        return count == null ? 0 : count;
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
