package com.nemonicworld.backoffice.logs.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.backoffice.logs.exception.AdminLogsException;
import com.nemonicworld.backoffice.logs.service.OpenSearchClient;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.support.AbstractReadOnlyIntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import java.util.concurrent.TimeoutException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@ExtendWith(OutputCaptureExtension.class)
class AdminLogsControllerIntegrationTest extends AbstractReadOnlyIntegrationTest {

    private static final long ADMIN_ID = 71L;
    private static final String ADMIN_LOGIN_ID = "logs-admin";
    private static final String ADMIN_NICKNAME = "Logs Admin";
    private static final String ADMIN_EMAIL = "logs-admin@example.com";
    private static final String SEARCH_PATH = "/api/v1/admin/logs/search";
    private static final String HISTOGRAM_PATH = "/api/v1/admin/logs/histogram";
    private static final String TERMS_WITH_SUBS_PATH = "/api/v1/admin/logs/terms-with-subs";
    private static final String TERMS_WITH_METRIC_PATH = "/api/v1/admin/logs/terms-with-metric";
    private static final String COMPOSITE_BUCKETS_PATH = "/api/v1/admin/logs/composite-buckets";
    private static final String FILTERED_METRICS_PATH = "/api/v1/admin/logs/filtered-metrics";
    private static final String DISTINCT_COUNT_PATH = "/api/v1/admin/logs/distinct-count";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private OpenSearchClient openSearchClient;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    @Test
    void unauthenticatedRequestReturnsAdminLogsErrorShape() throws Exception {
        mockMvc.perform(post(SEARCH_PATH).contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.code").value("ADMIN_LOGS_UNAUTHORIZED"))
            .andExpect(jsonPath("$.timestamp").isNotEmpty());
    }

    @Test
    @WithMockUser(roles = "USER")
    void nonAdminRequestReturnsForbiddenErrorShape() throws Exception {
        mockMvc.perform(post(SEARCH_PATH).contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ADMIN_LOGS_FORBIDDEN"))
            .andExpect(jsonPath("$.timestamp").isNotEmpty());
    }

    @Test
    void searchReturnsMappedOpenSearchResponse(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 87,
              "hits": {
                "total": { "value": 12345, "relation": "gte" },
                "hits": [
                  {
                    "_id": "doc-1",
                    "_index": "biz-events-2026.05.14",
                    "_source": {
                      "@timestamp": "2026-05-14T00:00:00Z",
                      "level": "ERROR",
                      "service": "api-server"
                    },
                    "sort": ["2026-05-14T00:00:00Z", "doc-1"]
                  }
                ]
              }
            }
            """));

        mockMvc
            .perform(post(SEARCH_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .header("X-Trace-Id", "logs-search-trace").contentType(MediaType.APPLICATION_JSON)
                .content(validSearchBody()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.total").value(12345))
            .andExpect(jsonPath("$.tookMs").value(87)).andExpect(jsonPath("$.hits.length()").value(1))
            .andExpect(jsonPath("$.hits[0].id").value("doc-1"))
            .andExpect(jsonPath("$.hits[0].index").value("biz-events-2026.05.14"))
            .andExpect(jsonPath("$.hits[0].source.level").value("ERROR"))
            .andExpect(jsonPath("$.nextSearchAfter[1]").value("doc-1"));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("logs-search-trace");
        assertThat(auditLog.path("metadata").path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("search");
        assertThat(auditLog.path("metadata").path("result_total").asLong()).isEqualTo(12345L);
    }

    @Test
    void timeoutReturnsGatewayTimeout() throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class)))
            .willThrow(AdminLogsException.timeout(new TimeoutException("timeout")));

        mockMvc
            .perform(post(SEARCH_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isGatewayTimeout()).andExpect(jsonPath("$.code").value("OPENSEARCH_TIMEOUT"));
    }

    @Test
    void histogramWithGroupByReturnsByFieldPerBucket(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 12,
              "hits": {"total": {"value": 234}, "hits": []},
              "aggregations": {
                "ts": {
                  "buckets": [
                    {
                      "key_as_string": "2026-05-14T00:00:00Z",
                      "key": 1747094400000,
                      "doc_count": 234,
                      "level": {"buckets": [{"key": "INFO", "doc_count": 100}]},
                      "by_field": {
                        "buckets": [
                          {"key": "relay_room_creation", "doc_count": 100},
                          {"key": "infinite_canvas_join", "doc_count": 50}
                        ]
                      }
                    }
                  ]
                }
              }
            }
            """));

        mockMvc
            .perform(post(HISTOGRAM_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .header("X-Trace-Id", "logs-histogram-trace").contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "index": "biz-events",
                      "query": "",
                      "filters": [],
                      "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                      "groupBy": "metadata.funnel_name"
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.buckets[0].total").value(234))
            .andExpect(jsonPath("$.buckets[0].byLevel.INFO").value(100))
            .andExpect(jsonPath("$.buckets[0].byField.relay_room_creation").value(100))
            .andExpect(jsonPath("$.buckets[0].byField.infinite_canvas_join").value(50));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("histogram");
    }

    @Test
    void termsWithSubsReturnsBucketsSortedByTotalDesc(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 33,
              "hits": {"total": {"value": 220}, "hits": []},
              "aggregations": {
                "groups": {
                  "buckets": [
                    {"key": "small", "doc_count": 80,
                      "started": {"doc_count": 70}, "completed": {"doc_count": 50}},
                    {"key": "large", "doc_count": 140,
                      "started": {"doc_count": 130}, "completed": {"doc_count": 78}}
                  ]
                }
              }
            }
            """));

        mockMvc
            .perform(post(TERMS_WITH_SUBS_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .header("X-Trace-Id", "logs-terms-subs-trace").contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "index": "biz-events",
                      "query": "",
                      "filters": [],
                      "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                      "groupBy": "metadata.funnel_name",
                      "size": 10,
                      "subFilters": [
                        {"name": "started", "query": "event_name:funnel_step_completed"},
                        {"name": "completed", "query": "event_name:funnel_goal_reached"}
                      ]
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.buckets[0].value").value("large"))
            .andExpect(jsonPath("$.buckets[0].total").value(140))
            .andExpect(jsonPath("$.buckets[0].sub.started").value(130))
            .andExpect(jsonPath("$.buckets[0].sub.completed").value(78))
            .andExpect(jsonPath("$.buckets[1].value").value("small"));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("terms-with-subs");
    }

    @Test
    void termsWithMetricReturnsBucketsSortedByFirstMetric(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 21,
              "hits": {"total": {"value": 1200}, "hits": []},
              "aggregations": {
                "groups": {
                  "buckets": [
                    {"key": "/relay-drawing/r1", "doc_count": 600,
                      "avgMs": {"value": 32000.0}},
                    {"key": "/relay-drawing/r2", "doc_count": 600,
                      "avgMs": {"value": 45120.5}}
                  ]
                }
              }
            }
            """));

        mockMvc
            .perform(post(TERMS_WITH_METRIC_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "index": "biz-events",
                      "query": "",
                      "filters": [],
                      "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                      "groupBy": "path",
                      "size": 30,
                      "metrics": [
                        {"type": "avg", "field": "metadata.time_on_page_ms", "name": "avgMs"}
                      ]
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.buckets[0].value").value("/relay-drawing/r2"))
            .andExpect(jsonPath("$.buckets[0].metrics.avgMs").value(45120.5));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("terms-with-metric");
    }

    @Test
    void compositeBucketsReturnsBucketsAndAfterKey(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 47,
              "hits": {"total": {"value": 500}, "hits": []},
              "aggregations": {
                "composite_buckets": {
                  "after_key": {
                    "metadata.funnel_name": "relay_room_creation",
                    "metadata.step_name": "review"
                  },
                  "buckets": [
                    {
                      "key": {"metadata.funnel_name": "relay_room_creation", "metadata.step_name": "settings"},
                      "doc_count": 142,
                      "minStepIndex": {"value": 0.0}
                    }
                  ]
                }
              }
            }
            """));

        mockMvc
            .perform(post(COMPOSITE_BUCKETS_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "index": "biz-events",
                      "query": "",
                      "filters": [],
                      "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                      "sources": ["metadata.funnel_name", "metadata.step_name"],
                      "size": 200,
                      "subAggs": [
                        {"type": "min", "field": "metadata.step_index", "name": "minStepIndex"}
                      ]
                    }
                    """))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.buckets[0].keys['metadata.funnel_name']").value("relay_room_creation"))
            .andExpect(jsonPath("$.buckets[0].count").value(142))
            .andExpect(jsonPath("$.buckets[0].sub.minStepIndex").value(0.0))
            .andExpect(jsonPath("$.afterKey['metadata.step_name']").value("review"));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("composite-buckets");
    }

    @Test
    void filteredMetricsReturnsCountAndOptionalMetricPerGroup(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 19,
              "hits": {"total": {"value": 288}, "hits": []},
              "aggregations": {
                "lobby": {"doc_count": 142, "metric": {"value": 18230.5}},
                "creation": {"doc_count": 90, "metric": {"value": 41200.0}},
                "noMetric": {"doc_count": 56}
              }
            }
            """));

        mockMvc
            .perform(post(FILTERED_METRICS_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "index": "biz-events",
                      "query": "",
                      "filters": [],
                      "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                      "groups": [
                        {"name": "lobby", "query": "event_name:room_lobby_abandoned",
                          "metric": {"type": "avg", "field": "metadata.wait_time_ms"}},
                        {"name": "creation", "query": "event_name:creation_abandoned",
                          "metric": {"type": "avg", "field": "metadata.elapsed_ms"}},
                        {"name": "noMetric", "query": "event_name:result_share_abandoned"}
                      ]
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.groups.lobby.count").value(142))
            .andExpect(jsonPath("$.groups.lobby.metric").value(18230.5))
            .andExpect(jsonPath("$.groups.creation.metric").value(41200.0))
            .andExpect(jsonPath("$.groups.noMetric.count").value(56))
            .andExpect(jsonPath("$.groups.noMetric.metric").doesNotExist());

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("filtered-metrics");
    }

    @Test
    void distinctCountReturnsCardinalityValue(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 8,
              "hits": {"total": {"value": 9999}, "hits": []},
              "aggregations": {"distinct": {"value": 1247}}
            }
            """));

        mockMvc.perform(post(DISTINCT_COUNT_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "index": "biz-events",
                  "query": "",
                  "filters": [],
                  "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                  "field": "uuid",
                  "precisionThreshold": 3000
                }
                """)).andExpect(status().isOk()).andExpect(jsonPath("$.value").value(1247));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("distinct-count");
    }

    @Test
    void distinctCountRejectsFieldOutsideWhitelist() throws Exception {
        mockMvc
            .perform(post(DISTINCT_COUNT_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "index": "biz-events",
                      "query": "",
                      "filters": [],
                      "timeRange": {"from": "2026-05-14T00:00:00Z", "to": "2026-05-15T00:00:00Z"},
                      "field": "service"
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("ADMIN_LOGS_INVALID_FIELD"));
    }

    @Test
    void upstreamFailureReturnsBadGateway() throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class)))
            .willThrow(AdminLogsException.upstream(new RuntimeException("upstream")));

        mockMvc
            .perform(post(SEARCH_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isBadGateway()).andExpect(jsonPath("$.code").value("OPENSEARCH_UPSTREAM_ERROR"));
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private String bearerAccessToken() {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(ADMIN_ID, ADMIN_LOGIN_ID, "encoded", ADMIN_NICKNAME, ADMIN_EMAIL,
            AdminRole.ADMIN, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private String validSearchBody() {
        return """
            {
              "index": "biz-events",
              "query": "level:ERROR AND service:api-server",
              "filters": [
                { "field": "service", "value": "api-server", "negate": false }
              ],
              "timeRange": {
                "from": "2026-05-14T00:00:00Z",
                "to": "2026-05-15T00:00:00Z"
              },
              "size": 50
            }
            """;
    }

    private JsonNode findAuditLog(CapturedOutput output, String eventName) throws Exception {
        for (String line : output.getOut().split("\\R")) {
            if (line.contains("\"event_name\":\"%s\"".formatted(eventName))) {
                return objectMapper.readTree(line.substring(line.indexOf('{')));
            }
        }

        throw new AssertionError("Audit log not found. eventName=" + eventName);
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
