package com.nemonicworld.backoffice.logs.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.backoffice.logs.exception.AdminLogsException;
import com.nemonicworld.backoffice.logs.service.OpenSearchClient;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import java.util.concurrent.TimeoutException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
@ExtendWith(OutputCaptureExtension.class)
class AdminLogsControllerIntegrationTest {

    private static final long ADMIN_ID = 71L;
    private static final String ADMIN_LOGIN_ID = "logs-admin";
    private static final String ADMIN_NICKNAME = "Logs Admin";
    private static final String ADMIN_EMAIL = "logs-admin@example.com";
    private static final String SEARCH_PATH = "/api/v1/admin/logs/search";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private OpenSearchClient openSearchClient;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    @Test
    void unauthenticatedRequestReturnsAdminLogsErrorShape() throws Exception {
        mockMvc.perform(post(SEARCH_PATH).contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.code").value("ADMIN_LOGS_UNAUTHORIZED"))
            .andExpect(jsonPath("$.timestamp").isNotEmpty());
    }

    @Test
    @WithMockUser(roles = "USER")
    void nonAdminRequestReturnsForbiddenErrorShape() throws Exception {
        mockMvc.perform(post(SEARCH_PATH).contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ADMIN_LOGS_FORBIDDEN"))
            .andExpect(jsonPath("$.timestamp").isNotEmpty());
    }

    @Test
    void searchReturnsMappedOpenSearchResponse(CapturedOutput output) throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class))).willReturn(objectMapper.readTree("""
            {
              "took": 87,
              "hits": {
                "total": { "value": 12345, "relation": "gte" },
                "hits": [
                  {
                    "_id": "doc-1",
                    "_index": "biz-events-2026.05.14",
                    "_source": {
                      "@timestamp": "2026-05-14T00:00:00Z",
                      "level": "ERROR",
                      "service": "api-server"
                    },
                    "sort": ["2026-05-14T00:00:00Z", "doc-1"]
                  }
                ]
              }
            }
            """));

        mockMvc
            .perform(post(SEARCH_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .header("X-Trace-Id", "logs-search-trace").contentType(MediaType.APPLICATION_JSON)
                .content(validSearchBody()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.total").value(12345))
            .andExpect(jsonPath("$.tookMs").value(87)).andExpect(jsonPath("$.hits.length()").value(1))
            .andExpect(jsonPath("$.hits[0].id").value("doc-1"))
            .andExpect(jsonPath("$.hits[0].index").value("biz-events-2026.05.14"))
            .andExpect(jsonPath("$.hits[0].source.level").value("ERROR"))
            .andExpect(jsonPath("$.nextSearchAfter[1]").value("doc-1"));

        JsonNode auditLog = findAuditLog(output, "admin_logs_query");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("logs-search-trace");
        assertThat(auditLog.path("metadata").path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(auditLog.path("metadata").path("endpoint").asText()).isEqualTo("search");
        assertThat(auditLog.path("metadata").path("result_total").asLong()).isEqualTo(12345L);
    }

    @Test
    void timeoutReturnsGatewayTimeout() throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class)))
            .willThrow(AdminLogsException.timeout(new TimeoutException("timeout")));

        mockMvc
            .perform(post(SEARCH_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isGatewayTimeout()).andExpect(jsonPath("$.code").value("OPENSEARCH_TIMEOUT"));
    }

    @Test
    void upstreamFailureReturnsBadGateway() throws Exception {
        given(openSearchClient.search(eq("biz-events-*"), any(JsonNode.class)))
            .willThrow(AdminLogsException.upstream(new RuntimeException("upstream")));

        mockMvc
            .perform(post(SEARCH_PATH).header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content(validSearchBody()))
            .andExpect(status().isBadGateway()).andExpect(jsonPath("$.code").value("OPENSEARCH_UPSTREAM_ERROR"));
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private String bearerAccessToken() {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(ADMIN_ID, ADMIN_LOGIN_ID, "encoded", ADMIN_NICKNAME, ADMIN_EMAIL,
            AdminRole.ADMIN, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private String validSearchBody() {
        return """
            {
              "index": "biz-events",
              "query": "level:ERROR AND service:api-server",
              "filters": [
                { "field": "service", "value": "api-server", "negate": false }
              ],
              "timeRange": {
                "from": "2026-05-14T00:00:00Z",
                "to": "2026-05-15T00:00:00Z"
              },
              "size": 50
            }
            """;
    }

    private JsonNode findAuditLog(CapturedOutput output, String eventName) throws Exception {
        for (String line : output.getOut().split("\\R")) {
            if (line.contains("\"event_name\":\"%s\"".formatted(eventName))) {
                return objectMapper.readTree(line.substring(line.indexOf('{')));
            }
        }

        throw new AssertionError("Audit log not found. eventName=" + eventName);
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
