-- 통합 테스트 ApplicationContext가 격리된 H2 in-memory DB에서 시작할 때 자동으로 적용되는 schema.
--
-- 이 스키마는 production main 코드가 JdbcTemplate으로 raw SQL을 던지는 비-JPA 테이블만 다룬다.
-- 즉 SystemParameterRepository, AdminUserRepository 등 JdbcTemplate 사용 리포지토리가 의존하는
-- 테이블이다. JPA @Entity로 매핑된 테이블(app_user, file_upload 등)은 Hibernate ddl-auto=create-drop
-- 이 자동 생성한다.
--
-- 기존에 각 통합 테스트 클래스가 자기 @BeforeEach 안에서 CREATE TABLE IF NOT EXISTS 로 같은 테이블을
-- 만들었고, 모든 컨텍스트가 같은 mem:nemonic-test DB를 공유했기 때문에 한 테스트가 만든 테이블을 다른
-- 테스트가 우연히 빌어 썼다. H2 DB가 컨텍스트별로 격리되면서 이 cross-context schema 의존이 깨졌으므로
-- production 코드가 의존하는 테이블은 schema.sql 로 모든 컨텍스트에 동일하게 적용한다.
--
-- 각 테스트의 inline CREATE TABLE IF NOT EXISTS 는 그대로 두어도 no-op 이므로 별도로 제거하지 않는다.

CREATE TABLE IF NOT EXISTS admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS backoffice_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(128) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL DEFAULT '{}',
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
