package com.nemonicworld.inquiry.controller;

import static org.hamcrest.Matchers.aMapWithSize;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
class AdminInquiryControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String ADMIN_LOGIN_ID = "inquiry-admin";
    private static final String SUPER_ADMIN_LOGIN_ID = "inquiry-super-admin";
    private static final String ADMIN_NICKNAME = "Inquiry Admin";
    private static final String ADMIN_EMAIL = "inquiry-admin@example.com";
    private static final String SUPER_ADMIN_EMAIL = "inquiry-super-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS app_user (
                id UUID NOT NULL PRIMARY KEY,
                nickname VARCHAR(10) NOT NULL,
                last_seen_at TIMESTAMP NOT NULL,
                birthday DATE NULL,
                birthtime TIME NULL,
                is_lunar BOOLEAN NULL,
                user_agent TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS cs_inquiry (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL,
                inquiry_type VARCHAR(32) NOT NULL,
                title VARCHAR(255) NOT NULL,
                content VARCHAR(1000) NULL,
                email VARCHAR(255) NULL,
                attachments TEXT NULL,
                meta TEXT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'new',
                assigned_to BIGINT NULL,
                response_note TEXT NULL,
                responded_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM cs_inquiry");
        jdbcTemplate.update("DELETE FROM app_user");
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE cs_inquiry ALTER COLUMN id RESTART WITH 100");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_EMAIL, AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsInquiryList() throws Exception {
        UUID userUuid = insertAppUser();
        LocalDateTime createdAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        insertInquiry(100L, userUuid, "error", "이전 오류 문의", "이전 문의 내용", "old@example.com", "new", createdAt);
        insertInquiry(101L, userUuid, "other", "최근 기타 문의", "최근 문의 내용", "new@example.com", "resolved", createdAt);

        mockMvc.perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.items[0].id").value(101L))
            .andExpect(jsonPath("$.data.items[0].userId").value(userUuid.toString()))
            .andExpect(jsonPath("$.data.items[0].type").value("other"))
            .andExpect(jsonPath("$.data.items[0].title").value("최근 기타 문의"))
            .andExpect(jsonPath("$.data.items[0].email").value("new@example.com"))
            .andExpect(jsonPath("$.data.items[0].status").value("resolved"))
            .andExpect(jsonPath("$.data.items[0].createdAt").isNotEmpty())
            .andExpect(jsonPath("$.data.items[0].updatedAt").isNotEmpty())
            .andExpect(jsonPath("$.data.items[0].content").doesNotExist())
            .andExpect(jsonPath("$.data.items[0].attachments").doesNotExist())
            .andExpect(jsonPath("$.data.items[0].meta").doesNotExist())
            .andExpect(jsonPath("$.data.items[0].responseNote").doesNotExist())
            .andExpect(jsonPath("$.data.items[1].id").value(100L)).andExpect(jsonPath("$.data.page").value(0))
            .andExpect(jsonPath("$.data.size").value(20)).andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.hasNext").value(false));
    }

    @Test
    void superAdminGetsInquiryList() throws Exception {
        UUID userUuid = insertAppUser();
        insertInquiry(100L, userUuid, "error", "오류 문의", "문의 내용", "user@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_EMAIL, AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].id").value(100L));
    }

    @Test
    void inquiryListRejectsUnauthenticatedRequest() throws Exception {
        mockMvc.perform(get("/api/v1/admin/inquiries")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void inquiryListFiltersByStatus() throws Exception {
        UUID userUuid = insertAppUser();
        insertInquiry(100L, userUuid, "error", "신규 문의", "문의 내용", "new@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));
        insertInquiry(101L, userUuid, "error", "처리 완료 문의", "문의 내용", "resolved@example.com", "resolved",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "new"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].id").value(100L))
            .andExpect(jsonPath("$.data.items[0].status").value("new"))
            .andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void inquiryListFiltersByType() throws Exception {
        UUID userUuid = insertAppUser();
        insertInquiry(100L, userUuid, "error", "오류 문의", "문의 내용", "error@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));
        insertInquiry(101L, userUuid, "feature_request", "기능 제안", "문의 내용", "feature@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("type", "feature_request"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].id").value(101L))
            .andExpect(jsonPath("$.data.items[0].type").value("feature_request"))
            .andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void inquiryListSearchesByKeyword() throws Exception {
        UUID userUuid = insertAppUser();
        insertInquiry(100L, userUuid, "error", "오류 문의", "결제가 완료되지 않았습니다.", "pay@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));
        insertInquiry(101L, userUuid, "other", "기타 문의", "다른 문의 내용", "other@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", "결제"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].id").value(100L)).andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void inquiryListFiltersByUserUuid() throws Exception {
        UUID targetUserUuid = insertAppUser();
        UUID otherUserUuid = insertAppUser();
        insertInquiry(100L, targetUserUuid, "error", "대상 사용자 문의", "문의 내용", "target@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));
        insertInquiry(101L, otherUserUuid, "other", "다른 사용자 문의", "문의 내용", "other@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("userUuid", targetUserUuid.toString()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].id").value(100L))
            .andExpect(jsonPath("$.data.items[0].userId").value(targetUserUuid.toString()))
            .andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void inquiryListAppliesPagination() throws Exception {
        UUID userUuid = insertAppUser();
        LocalDateTime createdAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        insertInquiry(100L, userUuid, "error", "첫 번째 문의", "문의 내용", "first@example.com", "new", createdAt);
        insertInquiry(101L, userUuid, "error", "두 번째 문의", "문의 내용", "second@example.com", "new", createdAt);
        insertInquiry(102L, userUuid, "error", "세 번째 문의", "문의 내용", "third@example.com", "new", createdAt);

        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("page", "1").queryParam("size", "1"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].id").value(101L)).andExpect(jsonPath("$.data.page").value(1))
            .andExpect(jsonPath("$.data.size").value(1)).andExpect(jsonPath("$.data.totalElements").value(3))
            .andExpect(jsonPath("$.data.hasNext").value(true));
    }

    @ParameterizedTest
    @CsvSource({"status,unknown", "type,unknown", "userUuid,not-a-uuid", "page,-1", "page,abc", "size,0", "size,51",
        "size,abc"})
    void inquiryListRejectsInvalidParameters(String parameterName, String parameterValue) throws Exception {
        mockMvc
            .perform(get("/api/v1/admin/inquiries").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam(parameterName, parameterValue))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminGetsInquiryDetail() throws Exception {
        UUID userUuid = insertAppUser();
        LocalDateTime createdAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        LocalDateTime respondedAt = createdAt.plusHours(1);
        insertInquiry(100L, userUuid, "error", "결제 오류 문의", "결제는 완료됐는데 서비스가 활성화되지 않았습니다.", "user@example.com",
            "in_progress", ADMIN_ID, "결제 내역 확인 중", respondedAt,
            "[\"https://cdn.example.com/1.png\",\"https://cdn.example.com/2.png\"]",
            "{\"userAgent\":\"MockMvc/1.0\",\"referer\":\"https://k14s208.p.ssafy.io/support\"}", createdAt);

        mockMvc
            .perform(
                get("/api/v1/admin/inquiries/{inquiryId}", 100L).header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.id").value(100L))
            .andExpect(jsonPath("$.data.userId").value(userUuid.toString()))
            .andExpect(jsonPath("$.data.type").value("error")).andExpect(jsonPath("$.data.title").value("결제 오류 문의"))
            .andExpect(jsonPath("$.data.content").value("결제는 완료됐는데 서비스가 활성화되지 않았습니다."))
            .andExpect(jsonPath("$.data.email").value("user@example.com"))
            .andExpect(jsonPath("$.data.attachments.length()").value(2))
            .andExpect(jsonPath("$.data.attachments[0]").value("https://cdn.example.com/1.png"))
            .andExpect(jsonPath("$.data.meta.userAgent").value("MockMvc/1.0"))
            .andExpect(jsonPath("$.data.meta.referer").value("https://k14s208.p.ssafy.io/support"))
            .andExpect(jsonPath("$.data.status").value("in_progress"))
            .andExpect(jsonPath("$.data.assignedTo").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.responseNote").value("결제 내역 확인 중"))
            .andExpect(jsonPath("$.data.respondedAt").isNotEmpty()).andExpect(jsonPath("$.data.createdAt").isNotEmpty())
            .andExpect(jsonPath("$.data.updatedAt").isNotEmpty());
    }

    @Test
    void superAdminGetsInquiryDetail() throws Exception {
        UUID userUuid = insertAppUser();
        insertInquiry(100L, userUuid, "error", "오류 문의", "문의 내용", "user@example.com", "new",
            LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS));

        mockMvc
            .perform(get("/api/v1/admin/inquiries/{inquiryId}", 100L).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_EMAIL, AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.id").value(100L));
    }

    @Test
    void inquiryDetailRejectsUnauthenticatedRequest() throws Exception {
        mockMvc.perform(get("/api/v1/admin/inquiries/{inquiryId}", 100L)).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void inquiryDetailRejectsUnknownId() throws Exception {
        mockMvc
            .perform(
                get("/api/v1/admin/inquiries/{inquiryId}", 999L).header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("고객 문의를 찾을 수 없습니다."));
    }

    @ParameterizedTest
    @CsvSource({"0", "-1", "abc"})
    void inquiryDetailRejectsInvalidId(String inquiryId) throws Exception {
        mockMvc
            .perform(get("/api/v1/admin/inquiries/{inquiryId}", inquiryId).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("문의 ID가 올바르지 않습니다."));
    }

    @Test
    void inquiryDetailReturnsEmptyAttachmentsAndMetaWhenStoredValuesAreNull() throws Exception {
        UUID userUuid = insertAppUser();
        LocalDateTime createdAt = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        insertInquiry(100L, userUuid, "other", "기타 문의", "문의 내용", "user@example.com", "new", null, null, null, null,
            null, createdAt);

        mockMvc
            .perform(
                get("/api/v1/admin/inquiries/{inquiryId}", 100L).header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.attachments.length()").value(0))
            .andExpect(jsonPath("$.data.meta").value(aMapWithSize(0)));
    }

    private void insertAdminUser(long id, String loginId, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", ADMIN_NICKNAME, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private UUID insertAppUser() {
        UUID userUuid = UUID.randomUUID();
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO app_user (
                id,
                nickname,
                last_seen_at,
                birthday,
                birthtime,
                is_lunar,
                user_agent,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, NULL, NULL, NULL, ?, ?, ?)
            """, userUuid, "익명", Timestamp.valueOf(now), "MockMvc/1.0", Timestamp.valueOf(now), Timestamp.valueOf(now));

        return userUuid;
    }

    private void insertInquiry(long id, UUID userUuid, String type, String title, String content, String email,
        String status, LocalDateTime createdAt) {
        insertInquiry(id, userUuid, type, title, content, email, status, null, "관리자 내부 메모", null,
            "[\"https://cdn.example.com/1.png\"]", "{\"source\":\"test\"}", createdAt);
    }

    private void insertInquiry(long id, UUID userUuid, String type, String title, String content, String email,
        String status, Long assignedTo, String responseNote, LocalDateTime respondedAt, String attachments, String meta,
        LocalDateTime createdAt) {
        jdbcTemplate.update("""
            INSERT INTO cs_inquiry (
                id,
                user_id,
                inquiry_type,
                title,
                content,
                email,
                attachments,
                meta,
                status,
                assigned_to,
                response_note,
                responded_at,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, id, userUuid, type, title, content, email, attachments, meta, status, assignedTo, responseNote,
            respondedAt == null ? null : Timestamp.valueOf(respondedAt), Timestamp.valueOf(createdAt),
            Timestamp.valueOf(createdAt));
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", ADMIN_NICKNAME, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    @TestConfiguration
    static class InquiryAdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
