package com.nemonicworld.inquiry.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.common.header.AnonymousUserHeaders;
import com.nemonicworld.support.AbstractReadOnlyIntegrationTest;
import com.nemonicworld.support.AppUserTestFixture;
import com.nemonicworld.user.entity.AppUser;
import com.nemonicworld.user.repository.UserRepository;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

class CsInquiryControllerIntegrationTest extends AbstractReadOnlyIntegrationTest {

    private static final String ANONYMOUS_USER_UUID_HEADER = AnonymousUserHeaders.ANONYMOUS_USER_UUID;

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private UserRepository userRepository;

    private AppUserTestFixture appUserFixture;

    @BeforeEach
    void prepareTables() {
        appUserFixture = new AppUserTestFixture(jdbcTemplate);
        appUserFixture.ensureTable();
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS cs_inquiry (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL,
                inquiry_type VARCHAR(32) NOT NULL,
                title VARCHAR(255) NOT NULL,
                content VARCHAR(1000) NULL,
                email VARCHAR(255) NULL,
                attachments TEXT NULL,
                meta TEXT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'new',
                assigned_to BIGINT NULL,
                response_note TEXT NULL,
                responded_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM cs_inquiry");
        appUserFixture.deleteAll();
        jdbcTemplate.execute("ALTER TABLE cs_inquiry ALTER COLUMN id RESTART WITH 100");
    }

    @Test
    void anonymousUserCreatesInquiry() throws Exception {
        UUID userUuid = createExistingUser();

        MvcResult result = mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()).header(HttpHeaders.USER_AGENT, "MangoApp/1.0")
                .header(HttpHeaders.REFERER, "https://nemonic.example/support").content(validRequestBody()))
            .andExpect(status().isCreated()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.id").exists()).andExpect(jsonPath("$.data.status").value("new"))
            .andExpect(jsonPath("$.data.createdAt").isNotEmpty()).andReturn();

        long inquiryId = readData(result).path("id").asLong();
        assertThat(countInquiries()).isEqualTo(1);
        assertThat(readStringColumn(inquiryId, "user_id")).isEqualTo(userUuid.toString());
        assertThat(readStringColumn(inquiryId, "inquiry_type")).isEqualTo("error");
        assertThat(readStringColumn(inquiryId, "title")).isEqualTo("Payment error");
        assertThat(readStringColumn(inquiryId, "status")).isEqualTo("new");

        JsonNode attachments = objectMapper.readTree(readStringColumn(inquiryId, "attachments"));
        assertThat(attachments).hasSize(2);
        JsonNode meta = objectMapper.readTree(readStringColumn(inquiryId, "meta"));
        assertThat(meta.path("device").asText()).isEqualTo("mobile");
        assertThat(meta.path("userAgent").asText()).isEqualTo("MangoApp/1.0");
        assertThat(meta.path("referer").asText()).isEqualTo("https://nemonic.example/support");
        assertThat(meta.path("createdAt").asText()).isNotBlank();
    }

    @Test
    void inquiryCreationRejectsInvalidUserUuidHeader() throws Exception {
        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, "not-a-uuid").content(validRequestBody()))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(countInquiries()).isZero();
    }

    @Test
    void inquiryCreationReturnsNotFoundWhenUserDoesNotExist() throws Exception {
        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, UUID.randomUUID().toString()).content(validRequestBody()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(countInquiries()).isZero();
    }

    @Test
    void inquiryCreationRejectsMissingTitle() throws Exception {
        UUID userUuid = createExistingUser();

        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()).content("""
                    {
                      "type": "error",
                      "content": "Payment did not activate."
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.errors.title").value("제목 필수"));

        assertThat(countInquiries()).isZero();
    }

    @Test
    void inquiryCreationRejectsUnsupportedType() throws Exception {
        UUID userUuid = createExistingUser();

        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()).content("""
                    {
                      "title": "Payment error",
                      "type": "etc",
                      "content": "Payment did not activate."
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("지원하지 않는 문의 유형입니다."));

        assertThat(countInquiries()).isZero();
    }

    @Test
    void inquiryCreationRejectsTooManyAttachments() throws Exception {
        UUID userUuid = createExistingUser();

        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()).content("""
                    {
                      "title": "Payment error",
                      "type": "error",
                      "attachments": [
                        "https://cdn.example.com/1.png",
                        "https://cdn.example.com/2.png",
                        "https://cdn.example.com/3.png",
                        "https://cdn.example.com/4.png"
                      ]
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.errors.attachments").value("첨부 파일은 최대 3개입니다."));

        assertThat(countInquiries()).isZero();
    }

    @Test
    void inquiryCreationRejectsContentTooLong() throws Exception {
        UUID userUuid = createExistingUser();
        String content = "a".repeat(1001);

        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()).content("""
                    {
                      "title": "Payment error",
                      "type": "error",
                      "content": "%s"
                    }
                    """.formatted(content)))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.errors.content").value("내용은 1000자 이하입니다."));

        assertThat(countInquiries()).isZero();
    }

    @Test
    void inquiryCreationRejectsInvalidEmail() throws Exception {
        UUID userUuid = createExistingUser();

        mockMvc
            .perform(post("/api/v1/inquiries").contentType(MediaType.APPLICATION_JSON)
                .header(ANONYMOUS_USER_UUID_HEADER, userUuid.toString()).content("""
                    {
                      "title": "Payment error",
                      "type": "error",
                      "email": "not-an-email"
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.errors.email").value("이메일 형식 오류"));

        assertThat(countInquiries()).isZero();
    }

    private UUID createExistingUser() {
        UUID userUuid = UUID.randomUUID();
        LocalDateTime createdAt = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        userRepository.saveAndFlush(AppUser.createAnonymous(userUuid, "MangoApp/1.0", createdAt));
        return userUuid;
    }

    private String validRequestBody() {
        return """
            {
              "title": "Payment error",
              "type": "error",
              "content": "The payment completed, but the service was not activated.",
              "email": "user@example.com",
              "attachments": [
                "https://cdn.example.com/1.png",
                "https://cdn.example.com/2.png"
              ],
              "meta": {
                "device": "mobile"
              }
            }
            """;
    }

    private JsonNode readData(MvcResult result) throws Exception {
        return objectMapper.readTree(result.getResponse().getContentAsString()).path("data");
    }

    private long countInquiries() {
        Long count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM cs_inquiry", Long.class);

        return count == null ? 0L : count;
    }

    private String readStringColumn(long inquiryId, String columnName) {
        return jdbcTemplate.queryForObject("SELECT %s FROM cs_inquiry WHERE id = ?".formatted(columnName), String.class,
            inquiryId);
    }

}
