package com.nemonicworld.auth.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

@IntegrationTest
@AutoConfigureMockMvc
@ExtendWith(OutputCaptureExtension.class)
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
class AuthControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "admin";
    private static final String ADMIN_PASSWORD = "password";
    private static final String ADMIN_NICKNAME = "운영자";
    private static final String ADMIN_EMAIL = "admin@example.com";
    private static final String NEW_ADMIN_LOGIN_ID = "manager01";
    private static final String NEW_ADMIN_PASSWORD = "Password123!";
    private static final String NEW_ADMIN_NICKNAME = "Operator";
    private static final String NEW_ADMIN_EMAIL = "manager01@example.com";
    private static final long TARGET_ADMIN_ID = 2L;
    private static final String TARGET_ADMIN_LOGIN_ID = "manager02";
    private static final String TARGET_ADMIN_PASSWORD = "Password456!";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private InMemoryAdminTokenStore adminTokenStore;

    @BeforeEach
    void prepareAdminUserTable() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        adminTokenStore.clear();
    }

    @Test
    void adminLoginReturnsAccessAndRefreshTokensAndUpdatesLastLoginAt(CapturedOutput output) throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);

        MvcResult result = mockMvc
            .perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
                .header("X-Trace-Id", "auth-login-success-test")
                .content(loginRequestBody(ADMIN_LOGIN_ID, ADMIN_PASSWORD)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("관리자 로그인 성공")).andExpect(jsonPath("$.data.accessToken").isNotEmpty())
            .andExpect(jsonPath("$.data.tokenType").value("Bearer"))
            .andExpect(jsonPath("$.data.expiresAt").isNotEmpty())
            .andExpect(jsonPath("$.data.refreshToken").isNotEmpty())
            .andExpect(jsonPath("$.data.refreshTokenExpiresAt").isNotEmpty())
            .andExpect(jsonPath("$.data.admin.id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.admin.loginId").value(ADMIN_LOGIN_ID))
            .andExpect(jsonPath("$.data.admin.nickname").value(ADMIN_NICKNAME))
            .andExpect(jsonPath("$.data.admin.email").value(ADMIN_EMAIL))
            .andExpect(jsonPath("$.data.admin.role").value("super_admin")).andReturn();

        JsonNode data = readData(result);
        assertThat(data.path("accessToken").asText()).contains(".");
        assertThat(data.path("refreshToken").asText()).isNotBlank();
        assertThat(readLastLoginAt(ADMIN_ID)).isNotNull();

        JsonNode auditLog = findAuditLog(output, "admin_login_success");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("level").asText()).isEqualTo("INFO");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("auth-login-success-test");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("super_admin");
        assertThat(metadata.path("target_type").asText()).isEqualTo("admin_account");
        assertThat(metadata.path("target_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("action").asText()).isEqualTo("login");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(auditLog.toString()).doesNotContain(ADMIN_PASSWORD);
    }

    @Test
    void adminRefreshTokenRotatesTokenPair() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "admin", null);
        AdminTokens tokens = loginAndReadTokens();

        MvcResult result = mockMvc
            .perform(post("/api/v1/auth/reissue").contentType(MediaType.APPLICATION_JSON)
                .content(refreshTokenRequestBody(tokens.refreshToken())))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("관리자 토큰 재발급 성공"))
            .andExpect(jsonPath("$.data.accessToken").isNotEmpty())
            .andExpect(jsonPath("$.data.refreshToken").isNotEmpty()).andReturn();

        AdminTokens rotatedTokens = readTokens(result);
        assertThat(rotatedTokens.accessToken()).isNotEqualTo(tokens.accessToken());
        assertThat(rotatedTokens.refreshToken()).isNotEqualTo(tokens.refreshToken());

        mockMvc.perform(post("/api/v1/auth/reissue").contentType(MediaType.APPLICATION_JSON)
            .content(refreshTokenRequestBody(tokens.refreshToken()))).andExpect(status().isUnauthorized());
        mockMvc
            .perform(post("/api/v1/auth/logout").header(HttpHeaders.AUTHORIZATION, bearer(rotatedTokens.accessToken()))
                .contentType(MediaType.APPLICATION_JSON).content(logoutRequestBody(rotatedTokens.refreshToken())))
            .andExpect(status().isOk());
    }

    @Test
    void adminLoginRejectsWrongPasswordWithoutExposingReason(CapturedOutput output) throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "admin", null);

        mockMvc
            .perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
                .header("X-Trace-Id", "auth-login-failure-test")
                .content(loginRequestBody(ADMIN_LOGIN_ID, "wrong-password")))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("관리자 인증에 실패했습니다."));

        assertThat(readLastLoginAt(ADMIN_ID)).isNull();

        JsonNode auditLog = findAuditLog(output, "admin_login_failed");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("level").asText()).isEqualTo("WARN");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("auth-login-failure-test");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("admin");
        assertThat(metadata.path("target_type").asText()).isEqualTo("admin_account");
        assertThat(metadata.path("target_id").asText()).isEqualTo(ADMIN_LOGIN_ID);
        assertThat(metadata.path("action").asText()).isEqualTo("login");
        assertThat(metadata.path("result").asText()).isEqualTo("failure");
        assertThat(auditLog.toString()).doesNotContain("wrong-password");
    }

    @Test
    void adminLoginRejectsDeletedAdmin() throws Exception {
        LocalDateTime deletedAt = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "admin", deletedAt);

        mockMvc
            .perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
                .content(loginRequestBody(ADMIN_LOGIN_ID, ADMIN_PASSWORD)))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("관리자 인증에 실패했습니다."));

        assertThat(readLastLoginAt(ADMIN_ID)).isNull();
    }
    @Test
    void superAdminFindsAdminDetail() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        AdminTokens tokens = loginAndReadTokens();

        mockMvc
            .perform(get("/api/v1/admins/{adminId}", ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
                bearer(tokens.accessToken())))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").isNotEmpty()).andExpect(jsonPath("$.data.id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.loginId").value(ADMIN_LOGIN_ID))
            .andExpect(jsonPath("$.data.role").value("super_admin"));
    }

    @Test
    void adminDetailReturnsUnauthorizedWhenTokenIsMissingInvalidOrBlacklisted() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        AdminTokens tokens = loginAndReadTokens();
        adminTokenStore.accessTokenBlacklist.add(readTokenClaims(tokens.accessToken()).tokenId());

        mockMvc.perform(get("/api/v1/admins/{adminId}", ADMIN_ID)).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").isNotEmpty());

        mockMvc
            .perform(
                get("/api/v1/admins/{adminId}", ADMIN_ID).header(HttpHeaders.AUTHORIZATION, bearer("invalid-token")))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        mockMvc
            .perform(get("/api/v1/admins/{adminId}", ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
                bearer(tokens.accessToken())))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }
    @Test
    void adminLogoutRevokesRefreshTokenAndBlacklistsAccessToken(CapturedOutput output) throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "admin", null);
        AdminTokens tokens = loginAndReadTokens();

        mockMvc
            .perform(post("/api/v1/auth/logout").header(HttpHeaders.AUTHORIZATION, bearer(tokens.accessToken()))
                .contentType(MediaType.APPLICATION_JSON).content(logoutRequestBody(tokens.refreshToken()))
                .header("X-Trace-Id", "auth-logout-test"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("관리자 로그아웃 성공")).andExpect(jsonPath("$.data").doesNotExist());

        mockMvc.perform(post("/api/v1/auth/reissue").contentType(MediaType.APPLICATION_JSON)
            .content(refreshTokenRequestBody(tokens.refreshToken()))).andExpect(status().isUnauthorized());
        mockMvc.perform(
            get("/api/v1/admins/{adminId}", ADMIN_ID).header(HttpHeaders.AUTHORIZATION, bearer(tokens.accessToken())))
            .andExpect(status().isUnauthorized());

        JsonNode auditLog = findAuditLog(output, "admin_logout");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("level").asText()).isEqualTo("INFO");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("auth-logout-test");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("admin");
        assertThat(metadata.path("target_type").asText()).isEqualTo("admin_account");
        assertThat(metadata.path("target_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("action").asText()).isEqualTo("logout");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(auditLog.toString()).doesNotContain(tokens.accessToken()).doesNotContain(tokens.refreshToken());
    }

    @Test
    void superAdminCreatesAdmin(CapturedOutput output) throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        String accessToken = loginAndReadAccessToken();

        MvcResult result = mockMvc
            .perform(post("/api/v1/admins").header(HttpHeaders.AUTHORIZATION, bearer(accessToken))
                .header("X-Trace-Id", "admin-create-audit-test").header("X-Forwarded-For", "10.10.20.31, 10.10.20.32")
                .contentType(MediaType.APPLICATION_JSON)
                .content(adminCreateRequestBody(NEW_ADMIN_LOGIN_ID, NEW_ADMIN_PASSWORD, NEW_ADMIN_NICKNAME,
                    NEW_ADMIN_EMAIL)))
            .andExpect(status().isCreated()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").isNotEmpty()).andExpect(jsonPath("$.data.id").isNumber())
            .andExpect(jsonPath("$.data.loginId").value(NEW_ADMIN_LOGIN_ID))
            .andExpect(jsonPath("$.data.nickname").value(NEW_ADMIN_NICKNAME))
            .andExpect(jsonPath("$.data.email").value(NEW_ADMIN_EMAIL))
            .andExpect(jsonPath("$.data.role").value("admin")).andReturn();

        String storedPasswordHash = readPasswordHash(NEW_ADMIN_LOGIN_ID);
        assertThat(passwordEncoder.matches(NEW_ADMIN_PASSWORD, storedPasswordHash)).isTrue();
        assertThat(storedPasswordHash).isNotEqualTo(NEW_ADMIN_PASSWORD);

        String createdAdminId = readData(result).path("id").asText();
        JsonNode auditLog = findAuditLog(output, "admin_account_create");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("level").asText()).isEqualTo("INFO");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("admin-create-audit-test");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("super_admin");
        assertThat(metadata.path("actor_ip").asText()).isEqualTo("10.10.20.31");
        assertThat(metadata.path("target_type").asText()).isEqualTo("admin_account");
        assertThat(metadata.path("target_id").asText()).isEqualTo(createdAdminId);
        assertThat(metadata.path("action").asText()).isEqualTo("create");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(metadata.path("after").path("login_id").asText()).isEqualTo(NEW_ADMIN_LOGIN_ID);
        assertThat(metadata.path("after").path("nickname").asText()).isEqualTo(NEW_ADMIN_NICKNAME);
        assertThat(metadata.path("after").path("role").asText()).isEqualTo("admin");
        assertThat(metadata.path("after").has("email")).isFalse();
        assertThat(auditLog.toString()).doesNotContain(NEW_ADMIN_PASSWORD).doesNotContain(NEW_ADMIN_EMAIL)
            .doesNotContain("password_hash");
    }

    @Test
    void superAdminFindsAdmins() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        insertAdminUser(TARGET_ADMIN_ID, TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD, "admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc.perform(get("/api/v1/admins").header(HttpHeaders.AUTHORIZATION, bearer(accessToken)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").isNotEmpty()).andExpect(jsonPath("$.data.length()").value(2))
            .andExpect(jsonPath("$.data[0].id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data[1].id").value(TARGET_ADMIN_ID));
    }

    @Test
    void superAdminChangesAdminPasswordAndRevokesTokens() throws Exception {
        String changedPassword = "Changed123!";
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        insertAdminUser(TARGET_ADMIN_ID, TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD, "admin", null);
        String accessToken = loginAndReadAccessToken();
        AdminTokens targetTokens = loginAndReadTokens(TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD);

        mockMvc
            .perform(patch("/api/v1/admins/{adminId}", TARGET_ADMIN_ID)
                .header(HttpHeaders.AUTHORIZATION, bearer(accessToken)).contentType(MediaType.APPLICATION_JSON)
                .content(passwordChangeRequestBody(changedPassword)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").isNotEmpty()).andExpect(jsonPath("$.data").doesNotExist());

        mockMvc
            .perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
                .content(loginRequestBody(TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD)))
            .andExpect(status().isUnauthorized());
        mockMvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
            .content(loginRequestBody(TARGET_ADMIN_LOGIN_ID, changedPassword))).andExpect(status().isOk());
        mockMvc.perform(post("/api/v1/auth/reissue").contentType(MediaType.APPLICATION_JSON)
            .content(refreshTokenRequestBody(targetTokens.refreshToken()))).andExpect(status().isUnauthorized());
        mockMvc.perform(get("/api/v1/admins/{adminId}", TARGET_ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
            bearer(targetTokens.accessToken()))).andExpect(status().isUnauthorized());
    }

    @Test
    void adminCreationRequiresSuperAdminRole() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc
            .perform(post("/api/v1/admins").header(HttpHeaders.AUTHORIZATION, bearer(accessToken))
                .contentType(MediaType.APPLICATION_JSON)
                .content(adminCreateRequestBody(NEW_ADMIN_LOGIN_ID, NEW_ADMIN_PASSWORD, NEW_ADMIN_NICKNAME,
                    NEW_ADMIN_EMAIL)))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminCreationRejectsDuplicateLoginId() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        insertAdminUser(2L, NEW_ADMIN_LOGIN_ID, NEW_ADMIN_PASSWORD, "admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc
            .perform(post("/api/v1/admins").header(HttpHeaders.AUTHORIZATION, bearer(accessToken))
                .contentType(MediaType.APPLICATION_JSON)
                .content(adminCreateRequestBody(NEW_ADMIN_LOGIN_ID, NEW_ADMIN_PASSWORD, NEW_ADMIN_NICKNAME,
                    NEW_ADMIN_EMAIL)))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminCreationValidatesRequestBody() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc
            .perform(post("/api/v1/admins").header(HttpHeaders.AUTHORIZATION, bearer(accessToken))
                .contentType(MediaType.APPLICATION_JSON)
                .content(adminCreateRequestBody("", "short", NEW_ADMIN_NICKNAME, "not-email")))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty()).andExpect(jsonPath("$.errors.loginId").exists())
            .andExpect(jsonPath("$.errors.password").exists()).andExpect(jsonPath("$.errors.email").exists());
    }

    @Test
    void superAdminDeletesAdminAndRevokesTokens(CapturedOutput output) throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        insertAdminUser(TARGET_ADMIN_ID, TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD, "admin", null);
        String accessToken = loginAndReadAccessToken();
        AdminTokens targetTokens = loginAndReadTokens(TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD);

        mockMvc
            .perform(delete("/api/v1/admins/{adminId}", TARGET_ADMIN_ID)
                .header(HttpHeaders.AUTHORIZATION, bearer(accessToken)).header("X-Trace-Id", "admin-delete-audit-test")
                .header("X-Real-IP", "10.10.20.41"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").isNotEmpty()).andExpect(jsonPath("$.data").doesNotExist());

        assertThat(readDeletedAt(TARGET_ADMIN_ID)).isNotNull();
        mockMvc
            .perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
                .content(loginRequestBody(TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD)))
            .andExpect(status().isUnauthorized());
        mockMvc.perform(get("/api/v1/admins/{adminId}", TARGET_ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
            bearer(targetTokens.accessToken()))).andExpect(status().isUnauthorized());
        mockMvc.perform(post("/api/v1/auth/reissue").contentType(MediaType.APPLICATION_JSON)
            .content(refreshTokenRequestBody(targetTokens.refreshToken()))).andExpect(status().isUnauthorized());

        JsonNode auditLog = findAuditLog(output, "admin_account_delete");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("level").asText()).isEqualTo("INFO");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("admin-delete-audit-test");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("super_admin");
        assertThat(metadata.path("actor_ip").asText()).isEqualTo("10.10.20.41");
        assertThat(metadata.path("target_type").asText()).isEqualTo("admin_account");
        assertThat(metadata.path("target_id").asText()).isEqualTo(String.valueOf(TARGET_ADMIN_ID));
        assertThat(metadata.path("action").asText()).isEqualTo("delete");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(metadata.path("before").path("login_id").asText()).isEqualTo(TARGET_ADMIN_LOGIN_ID);
        assertThat(metadata.path("before").path("role").asText()).isEqualTo("admin");
        assertThat(metadata.path("before").has("email")).isFalse();
        assertThat(auditLog.toString()).doesNotContain(TARGET_ADMIN_PASSWORD).doesNotContain(ADMIN_EMAIL)
            .doesNotContain("password_hash").doesNotContain(targetTokens.accessToken())
            .doesNotContain(targetTokens.refreshToken());
    }

    @Test
    void adminDeletionRequiresSuperAdminRole() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "admin", null);
        insertAdminUser(TARGET_ADMIN_ID, TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD, "admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc
            .perform(delete("/api/v1/admins/{adminId}", TARGET_ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
                bearer(accessToken)))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(readDeletedAt(TARGET_ADMIN_ID)).isNull();
    }

    @Test
    void adminDeletionRejectsSelfDelete() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc
            .perform(
                delete("/api/v1/admins/{adminId}", ADMIN_ID).header(HttpHeaders.AUTHORIZATION, bearer(accessToken)))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(readDeletedAt(ADMIN_ID)).isNull();
    }

    @Test
    void adminDeletionRejectsSuperAdminTarget() throws Exception {
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        insertAdminUser(TARGET_ADMIN_ID, TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD, "super_admin", null);
        String accessToken = loginAndReadAccessToken();

        mockMvc
            .perform(delete("/api/v1/admins/{adminId}", TARGET_ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
                bearer(accessToken)))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(readDeletedAt(TARGET_ADMIN_ID)).isNull();
    }

    @Test
    void adminDeletionRejectsMissingOrDeletedTarget() throws Exception {
        LocalDateTime deletedAt = LocalDateTime.now().minusHours(1).truncatedTo(ChronoUnit.SECONDS);
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_PASSWORD, "super_admin", null);
        insertAdminUser(TARGET_ADMIN_ID, TARGET_ADMIN_LOGIN_ID, TARGET_ADMIN_PASSWORD, "admin", deletedAt);
        String accessToken = loginAndReadAccessToken();

        mockMvc.perform(delete("/api/v1/admins/{adminId}", 999L).header(HttpHeaders.AUTHORIZATION, bearer(accessToken)))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        mockMvc
            .perform(delete("/api/v1/admins/{adminId}", TARGET_ADMIN_ID).header(HttpHeaders.AUTHORIZATION,
                bearer(accessToken)))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    private void insertAdminUser(long id, String loginId, String rawPassword, String role, LocalDateTime deletedAt) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);

        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, ?)
            """, id, loginId, passwordEncoder.encode(rawPassword), ADMIN_NICKNAME, ADMIN_EMAIL, role,
            Timestamp.valueOf(now), Timestamp.valueOf(now), deletedAt == null ? null : Timestamp.valueOf(deletedAt));
    }

    private String loginAndReadAccessToken() throws Exception {
        return loginAndReadTokens().accessToken();
    }

    private AdminTokens loginAndReadTokens() throws Exception {
        return loginAndReadTokens(ADMIN_LOGIN_ID, ADMIN_PASSWORD);
    }

    private AdminTokens loginAndReadTokens(String loginId, String password) throws Exception {
        MvcResult result = mockMvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON)
            .content(loginRequestBody(loginId, password))).andExpect(status().isOk()).andReturn();

        return readTokens(result);
    }

    private AdminTokens readTokens(MvcResult result) throws Exception {
        JsonNode data = readData(result);

        return new AdminTokens(data.path("accessToken").asText(), data.path("refreshToken").asText());
    }

    private AdminTokenClaims readTokenClaims(String accessToken) throws Exception {
        String[] tokenParts = accessToken.split("\\.");
        JsonNode payload = objectMapper.readTree(Base64Url.decode(tokenParts[1]));

        return new AdminTokenClaims(payload.path("sub").asLong(), payload.path("login_id").asText(), null,
            payload.path("jti").asText(), Instant.ofEpochSecond(payload.path("iat").asLong()),
            Instant.ofEpochSecond(payload.path("exp").asLong()));
    }

    private String loginRequestBody(String loginId, String password) {
        return """
            {
              "loginId": "%s",
              "password": "%s"
            }
            """.formatted(loginId, password);
    }

    private String adminCreateRequestBody(String loginId, String password, String nickname, String email) {
        return """
            {
              "loginId": "%s",
              "password": "%s",
              "nickname": "%s",
              "email": "%s"
            }
            """.formatted(loginId, password, nickname, email);
    }

    private String passwordChangeRequestBody(String password) {
        return """
            {
              "password": "%s"
            }
            """.formatted(password);
    }

    private String refreshTokenRequestBody(String refreshToken) {
        return """
            {
              "refreshToken": "%s"
            }
            """.formatted(refreshToken);
    }

    private String logoutRequestBody(String refreshToken) {
        return refreshTokenRequestBody(refreshToken);
    }

    private String bearer(String accessToken) {
        return "Bearer %s".formatted(accessToken);
    }

    private LocalDateTime readLastLoginAt(long id) {
        return jdbcTemplate.queryForObject("SELECT last_login_at FROM admin_user WHERE id = ?",
            (resultSet, rowNumber) -> {
                Timestamp timestamp = resultSet.getTimestamp("last_login_at");
                return timestamp == null ? null : timestamp.toLocalDateTime();
            }, id);
    }

    private LocalDateTime readDeletedAt(long id) {
        return jdbcTemplate.queryForObject("SELECT deleted_at FROM admin_user WHERE id = ?", (resultSet, rowNumber) -> {
            Timestamp timestamp = resultSet.getTimestamp("deleted_at");
            return timestamp == null ? null : timestamp.toLocalDateTime();
        }, id);
    }

    private String readPasswordHash(String loginId) {
        return jdbcTemplate.queryForObject("SELECT password_hash FROM admin_user WHERE login_id = ?", String.class,
            loginId);
    }

    private JsonNode readData(MvcResult result) throws Exception {
        return objectMapper.readTree(result.getResponse().getContentAsString()).path("data");
    }

    private JsonNode findAuditLog(CapturedOutput output, String eventName) throws Exception {
        for (String line : output.getOut().split("\\R")) {
            if (line.contains("\"event_name\":\"%s\"".formatted(eventName))) {
                return objectMapper.readTree(line.substring(line.indexOf('{')));
            }
        }

        throw new AssertionError("Audit log not found. eventName=" + eventName);
    }

    private record AdminTokens(String accessToken, String refreshToken) {
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        InMemoryAdminTokenStore adminTokenStore() {
            return new InMemoryAdminTokenStore();
        }
    }

    static class InMemoryAdminTokenStore implements AdminTokenStore {

        private final Map<String, StoredAdminRefreshToken> refreshTokens = new ConcurrentHashMap<>();
        private final Set<String> accessTokenBlacklist = ConcurrentHashMap.newKeySet();
        private final Map<Long, Instant> accessRevokedAfter = new ConcurrentHashMap<>();

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            String refreshToken = UUID.randomUUID().toString();
            Instant expiresAt = Instant.now().plusSeconds(14 * 24 * 60 * 60);
            refreshTokens.put(refreshToken, new StoredAdminRefreshToken(adminUser.getId(), expiresAt));

            return new IssuedAdminRefreshToken(refreshToken, OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            StoredAdminRefreshToken storedToken = refreshTokens.get(refreshToken);
            if (storedToken == null || storedToken.isExpired(Instant.now())) {
                return Optional.empty();
            }

            return Optional.of(storedToken);
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
            refreshTokens.remove(refreshToken);
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
            refreshTokens.entrySet().removeIf(entry -> entry.getValue().adminId().equals(adminId));
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
            if (claims.tokenId() != null) {
                accessTokenBlacklist.add(claims.tokenId());
            }
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
            accessRevokedAfter.put(adminId, revokedAt);
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            if (claims.tokenId() != null && accessTokenBlacklist.contains(claims.tokenId())) {
                return true;
            }

            Instant revokedAfter = accessRevokedAfter.get(claims.adminId());
            return revokedAfter != null && !claims.issuedAt().isAfter(revokedAfter);
        }

        void clear() {
            refreshTokens.clear();
            accessTokenBlacklist.clear();
            accessRevokedAfter.clear();
        }
    }

    private static final class Base64Url {

        private Base64Url() {
        }

        static byte[] decode(String value) {
            return java.util.Base64.getUrlDecoder().decode(value);
        }
    }
}
