package com.nemonicworld.backoffice.flipbook.controller;

import static org.mockito.BDDMockito.given;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.flipbook.redis.FlipbookRoomParticipant;
import com.nemonicworld.flipbook.redis.FlipbookRoomState;
import com.nemonicworld.flipbook.redis.FlipbookRoomStatus;
import com.nemonicworld.flipbook.repository.FlipbookRoomRepository;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
class BackofficeFlipbookRoomControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "flipbook-room-admin";
    private static final String ADMIN_NICKNAME = "Flipbook Admin";
    private static final String ADMIN_EMAIL = "flipbook-admin@example.com";
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String SUPER_ADMIN_LOGIN_ID = "flipbook-room-super-admin";
    private static final String SUPER_ADMIN_NICKNAME = "Super Flipbook Admin";
    private static final String SUPER_ADMIN_EMAIL = "flipbook-super-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private FlipbookRoomRepository flipbookRoomRepository;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
            AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsActiveFlipbookRoomList() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(flipbookRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("FB3K9Q", FlipbookRoomStatus.WAITING, 1, null, null, null, base),
                roomState("FC4M8N", FlipbookRoomStatus.PLAYING, 4, 3, 8, base.plusMinutes(1), base.plusMinutes(1)),
                roomState("FD5P7R", FlipbookRoomStatus.FINISHED, 3, 8, 8, base.plusMinutes(2), base.plusMinutes(2))));

        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("활성 플립북 방 목록 조회 성공"))
            .andExpect(jsonPath("$.data.items.length()").value(3)).andExpect(jsonPath("$.data.totalElements").value(3))
            .andExpect(jsonPath("$.data.page").value(0)).andExpect(jsonPath("$.data.size").value(20))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("FD5P7R"))
            .andExpect(jsonPath("$.data.items[0].status").value("FINISHED"))
            .andExpect(jsonPath("$.data.items[0].participantCount").value(3))
            .andExpect(jsonPath("$.data.items[0].currentRound").value(8))
            .andExpect(jsonPath("$.data.items[0].totalRounds").value(8))
            .andExpect(jsonPath("$.data.items[0].gameStartedAt").value("2026-05-09T12:02:00"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("FC4M8N"))
            .andExpect(jsonPath("$.data.items[2].roomCode").value("FB3K9Q"))
            .andExpect(jsonPath("$.data.items[2].currentRound").value(org.hamcrest.Matchers.nullValue()))
            .andExpect(jsonPath("$.data.items[2].gameStartedAt").value(org.hamcrest.Matchers.nullValue()));
    }

    @Test
    void closedRoomsAreExcluded() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(flipbookRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("FA2B3C", FlipbookRoomStatus.WAITING, 1, null, null, null, base),
                roomState("FZ9Y8X", FlipbookRoomStatus.CLOSED, 0, 8, 8, base.plusMinutes(5), base.plusMinutes(5))));

        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("FA2B3C"));
    }

    @ParameterizedTest
    @EnumSource(value = FlipbookRoomStatus.class, names = {"WAITING", "PLAYING", "FINISHED"})
    void filtersByStatus(FlipbookRoomStatus roomStatus) throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        String expectedRoomCode = roomCodeFor(roomStatus);
        given(flipbookRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("FA2B3C", FlipbookRoomStatus.WAITING, 1, null, null, null, base),
                roomState("FB3K9Q", FlipbookRoomStatus.PLAYING, 4, 2, 8, base.plusMinutes(1), base.plusMinutes(1)),
                roomState("FC4M8N", FlipbookRoomStatus.FINISHED, 3, 8, 8, base.plusMinutes(2), base.plusMinutes(2))));

        mockMvc
            .perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", roomStatus.name()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.totalElements").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value(expectedRoomCode))
            .andExpect(jsonPath("$.data.items[0].status").value(roomStatus.name()));
    }

    @Test
    void rejectsClosedStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "CLOSED"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("조회할 수 없는 플립북 방 상태입니다."));
    }

    @Test
    void rejectsInvalidStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "INVALID"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("조회할 수 없는 플립북 방 상태입니다."));
    }

    @Test
    void sortsByCreatedAtDescendingAndRoomCodeAscending() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(flipbookRoomRepository.findAllActiveRooms()).willReturn(
            List.of(roomState("FC4M8N", FlipbookRoomStatus.WAITING, 1, null, null, null, base.minusMinutes(10)),
                roomState("FA2B3C", FlipbookRoomStatus.WAITING, 1, null, null, null, base),
                roomState("FB3K9Q", FlipbookRoomStatus.WAITING, 1, null, null, null, base)));

        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].roomCode").value("FA2B3C"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("FB3K9Q"))
            .andExpect(jsonPath("$.data.items[2].roomCode").value("FC4M8N"));
    }

    @Test
    void paginatesResults() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(flipbookRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("FA2B3C", FlipbookRoomStatus.WAITING, 1, null, null, null, base),
                roomState("FB3K9Q", FlipbookRoomStatus.WAITING, 1, null, null, null, base.minusSeconds(1)),
                roomState("FC4M8N", FlipbookRoomStatus.WAITING, 1, null, null, null, base.minusSeconds(2)),
                roomState("FD5P7R", FlipbookRoomStatus.WAITING, 1, null, null, null, base.minusSeconds(3)),
                roomState("FE6S8T", FlipbookRoomStatus.WAITING, 1, null, null, null, base.minusSeconds(4))));

        mockMvc
            .perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("page", "1").queryParam("size", "2"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2))
            .andExpect(jsonPath("$.data.totalElements").value(5)).andExpect(jsonPath("$.data.page").value(1))
            .andExpect(jsonPath("$.data.size").value(2)).andExpect(jsonPath("$.data.items[0].roomCode").value("FC4M8N"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("FD5P7R"));
    }

    @Test
    void clampsSizeToMaximum() throws Exception {
        given(flipbookRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "9999")).andExpect(status().isOk()).andExpect(jsonPath("$.data.size").value(100));
    }

    @Test
    void rejectsInvalidPageAndSize() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("page", "-1")).andExpect(status().isBadRequest());
        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "0")).andExpect(status().isBadRequest());
        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("page", "abc")).andExpect(status().isBadRequest());
        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "abc")).andExpect(status().isBadRequest());
    }

    @Test
    void rejectsUnauthenticatedRequest() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void superAdminGetsActiveFlipbookRoomList() throws Exception {
        given(flipbookRoomRepository.findAllActiveRooms()).willReturn(
            List.of(roomState("FA2B3C", FlipbookRoomStatus.WAITING, 1, null, null, null, LocalDateTime.now())));

        mockMvc
            .perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("FA2B3C"));
    }

    @Test
    void returnsEmptyListWhenNoActiveRooms() throws Exception {
        given(flipbookRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(get("/api/v1/backoffice/flipbook-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(0))
            .andExpect(jsonPath("$.data.totalElements").value(0));
    }

    private FlipbookRoomState roomState(String roomCode, FlipbookRoomStatus status, int participantCount,
        Integer currentRound, Integer totalRounds, LocalDateTime gameStartedAt, LocalDateTime createdAt) {
        List<FlipbookRoomParticipant> participants = participants(participantCount, createdAt);
        LocalDateTime roundStartedAt = currentRound == null ? null : gameStartedAt;
        LocalDateTime roundDeadlineAt = roundStartedAt == null ? null : roundStartedAt.plusSeconds(45);

        return new FlipbookRoomState(roomCode, status, "00000000-0000-0000-0000-000000000000", 45, 2, 6, currentRound,
            totalRounds, roundStartedAt, roundDeadlineAt, gameStartedAt, List.of(), participants, createdAt, createdAt,
            List.of());
    }

    private List<FlipbookRoomParticipant> participants(int count, LocalDateTime joinedAt) {
        if (count <= 0) {
            return List.of();
        }

        return java.util.stream.IntStream.range(0, count).mapToObj(index -> new FlipbookRoomParticipant("user-" + index,
            "닉네임" + index, index == 0, index, true, null, joinedAt)).toList();
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", nickname, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private String roomCodeFor(FlipbookRoomStatus status) {
        return switch (status) {
            case WAITING -> "FA2B3C";
            case PLAYING -> "FB3K9Q";
            case FINISHED -> "FC4M8N";
            case CLOSED -> "FZ9Y8X";
        };
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
