package com.nemonicworld.backoffice.relay.controller;

import static org.mockito.BDDMockito.given;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.relay.entity.RelayDrawingPart;
import com.nemonicworld.relay.entity.RelayRoomStatus;
import com.nemonicworld.relay.redis.RelayRoomParticipant;
import com.nemonicworld.relay.redis.RelayRoomState;
import com.nemonicworld.relay.repository.RelayRoomRepository;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
class BackofficeRelayRoomControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "relay-room-admin";
    private static final String ADMIN_NICKNAME = "Relay Admin";
    private static final String ADMIN_EMAIL = "relay-admin@example.com";
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String SUPER_ADMIN_LOGIN_ID = "relay-room-super-admin";
    private static final String SUPER_ADMIN_NICKNAME = "Super Relay Admin";
    private static final String SUPER_ADMIN_EMAIL = "relay-super-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private RelayRoomRepository relayRoomRepository;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
            AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsActiveRelayRoomList() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM01", RelayRoomStatus.WAITING, 1, null, base),
                roomState("ROOM02", RelayRoomStatus.PLAYING, 4, base.plusMinutes(1), base.plusMinutes(1)),
                roomState("ROOM03", RelayRoomStatus.FINALIZING, 5, base.plusMinutes(2), base.plusMinutes(2)),
                roomState("ROOM04", RelayRoomStatus.FINISHED, 3, base.plusMinutes(3), base.plusMinutes(3))));

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("활성 릴레이 드로잉 방 목록 조회 성공"))
            .andExpect(jsonPath("$.data.items.length()").value(4)).andExpect(jsonPath("$.data.totalElements").value(4))
            .andExpect(jsonPath("$.data.page").value(0)).andExpect(jsonPath("$.data.size").value(20))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM04"))
            .andExpect(jsonPath("$.data.items[0].status").value("FINISHED"))
            .andExpect(jsonPath("$.data.items[0].participantCount").value(3))
            .andExpect(jsonPath("$.data.items[0].gameStartedAt").value("2026-05-09T12:03:00"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("ROOM03"))
            .andExpect(jsonPath("$.data.items[2].roomCode").value("ROOM02"))
            .andExpect(jsonPath("$.data.items[3].roomCode").value("ROOM01"))
            .andExpect(jsonPath("$.data.items[3].gameStartedAt").value(org.hamcrest.Matchers.nullValue()));
    }

    @Test
    void closedRoomsAreExcluded() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        // 레포지토리는 이미 CLOSED를 거른 결과를 반환하지만, 서비스 계약상 들어와도 응답에 노출되지 않는지 확인합니다.
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ALIVE1", RelayRoomStatus.WAITING, 1, null, base),
                roomState("CLOSED1", RelayRoomStatus.CLOSED, 0, base.plusMinutes(5), base.plusMinutes(5))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "WAITING"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ALIVE1"));
    }

    @Test
    void filtersByStatus() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_W", RelayRoomStatus.WAITING, 1, null, base),
                roomState("ROOM_P", RelayRoomStatus.PLAYING, 4, base.plusMinutes(1), base.plusMinutes(1))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "PLAYING"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.totalElements").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_P"))
            .andExpect(jsonPath("$.data.items[0].status").value("PLAYING"));
    }

    @Test
    void rejectsClosedStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "CLOSED"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void rejectsInvalidStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "INVALID"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void sortsByCreatedAtDescending() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("OLDEST", RelayRoomStatus.WAITING, 1, null, base.minusMinutes(10)),
                roomState("NEWEST", RelayRoomStatus.WAITING, 1, null, base),
                roomState("MIDDLE", RelayRoomStatus.WAITING, 1, null, base.minusMinutes(5))));

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].roomCode").value("NEWEST"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("MIDDLE"))
            .andExpect(jsonPath("$.data.items[2].roomCode").value("OLDEST"));
    }

    @Test
    void paginatesResults() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_A", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(0)),
                roomState("ROOM_B", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(1)),
                roomState("ROOM_C", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(2)),
                roomState("ROOM_D", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(3)),
                roomState("ROOM_E", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(4))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("page", "1").queryParam("size", "2"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2))
            .andExpect(jsonPath("$.data.totalElements").value(5)).andExpect(jsonPath("$.data.page").value(1))
            .andExpect(jsonPath("$.data.size").value(2)).andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_C"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("ROOM_D"));
    }

    @Test
    void clampsSizeToMaximum() throws Exception {
        given(relayRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "9999")).andExpect(status().isOk()).andExpect(jsonPath("$.data.size").value(100));
    }

    @Test
    void rejectsNegativePage() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("page", "-1")).andExpect(status().isBadRequest());
    }

    @Test
    void rejectsZeroSize() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "0")).andExpect(status().isBadRequest());
    }

    @Test
    void rejectsUnauthenticatedRequest() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/relay-rooms")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void superAdminGetsActiveRelayRoomList() throws Exception {
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_S", RelayRoomStatus.WAITING, 1, null, LocalDateTime.now())));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_S"));
    }

    @Test
    void returnsEmptyListWhenNoActiveRooms() throws Exception {
        given(relayRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(0))
            .andExpect(jsonPath("$.data.totalElements").value(0));
    }

    private RelayRoomState roomState(String roomCode, RelayRoomStatus status, int participantCount,
        LocalDateTime gameStartedAt, LocalDateTime createdAt) {
        List<RelayRoomParticipant> participants = participants(participantCount, createdAt);
        RelayDrawingPart currentPart = status == RelayRoomStatus.PLAYING ? RelayDrawingPart.FACE : null;

        return new RelayRoomState(roomCode, status, "00000000-0000-0000-0000-000000000000", 60, 2, 6, currentPart,
            participants, List.of(), null, null, gameStartedAt, createdAt, createdAt, List.of());
    }

    private List<RelayRoomParticipant> participants(int count, LocalDateTime joinedAt) {
        if (count <= 0) {
            return List.of();
        }

        return java.util.stream.IntStream.range(0, count).mapToObj(
            index -> new RelayRoomParticipant("user-" + index, "닉네임" + index, index == 0, index, true, null, joinedAt))
            .toList();
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", nickname, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
