package com.nemonicworld.backoffice.relay.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.then;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.relay.entity.RelayDrawingPart;
import com.nemonicworld.relay.entity.RelayRoomStatus;
import com.nemonicworld.relay.redis.RelayRoomParticipant;
import com.nemonicworld.relay.redis.RelayRoomState;
import com.nemonicworld.relay.repository.RelayRoomRepository;
import com.nemonicworld.relay.service.support.RelayInviteMetadataSyncService;
import com.nemonicworld.relay.websocket.RelayRoomEventPublisher;
import com.nemonicworld.support.AbstractReadOnlyIntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.mockito.ArgumentCaptor;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@ExtendWith(OutputCaptureExtension.class)
class BackofficeRelayRoomControllerIntegrationTest extends AbstractReadOnlyIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "relay-room-admin";
    private static final String ADMIN_NICKNAME = "Relay Admin";
    private static final String ADMIN_EMAIL = "relay-admin@example.com";
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String SUPER_ADMIN_LOGIN_ID = "relay-room-super-admin";
    private static final String SUPER_ADMIN_NICKNAME = "Super Relay Admin";
    private static final String SUPER_ADMIN_EMAIL = "relay-super-admin@example.com";
    private static final long VIEWER_ID = 3L;
    private static final String VIEWER_LOGIN_ID = "relay-room-viewer";
    private static final String VIEWER_NICKNAME = "Relay Viewer";
    private static final String VIEWER_EMAIL = "relay-viewer@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private RelayRoomRepository relayRoomRepository;

    @MockitoBean
    private RelayInviteMetadataSyncService relayInviteMetadataSyncService;

    @MockitoBean
    private RelayRoomEventPublisher relayRoomEventPublisher;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
            AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsActiveRelayRoomList() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM01", RelayRoomStatus.WAITING, 1, null, base),
                roomState("ROOM02", RelayRoomStatus.PLAYING, 4, base.plusMinutes(1), base.plusMinutes(1)),
                roomState("ROOM03", RelayRoomStatus.FINALIZING, 5, base.plusMinutes(2), base.plusMinutes(2)),
                roomState("ROOM04", RelayRoomStatus.FINISHED, 3, base.plusMinutes(3), base.plusMinutes(3))));

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("활성 릴레이 드로잉 방 목록 조회 성공"))
            .andExpect(jsonPath("$.data.items.length()").value(3)).andExpect(jsonPath("$.data.totalElements").value(3))
            .andExpect(jsonPath("$.data.page").value(0)).andExpect(jsonPath("$.data.size").value(20))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM03"))
            .andExpect(jsonPath("$.data.items[0].status").value("FINALIZING"))
            .andExpect(jsonPath("$.data.items[0].participantCount").value(5))
            .andExpect(jsonPath("$.data.items[0].gameStartedAt").value("2026-05-09T12:02:00"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("ROOM02"))
            .andExpect(jsonPath("$.data.items[2].roomCode").value("ROOM01"))
            .andExpect(jsonPath("$.data.items[2].gameStartedAt").value(org.hamcrest.Matchers.nullValue()));
    }

    @Test
    void closedRoomsAreExcluded() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        // 레포지토리는 이미 CLOSED를 거른 결과를 반환하지만, 서비스 계약상 들어와도 응답에 노출되지 않는지 확인합니다.
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ALIVE1", RelayRoomStatus.WAITING, 1, null, base),
                roomState("CLOSED1", RelayRoomStatus.CLOSED, 0, base.plusMinutes(5), base.plusMinutes(5))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "WAITING"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ALIVE1"));
    }

    @Test
    void filtersByStatus() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_W", RelayRoomStatus.WAITING, 1, null, base),
                roomState("ROOM_P", RelayRoomStatus.PLAYING, 4, base.plusMinutes(1), base.plusMinutes(1))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "PLAYING"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.totalElements").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_P"))
            .andExpect(jsonPath("$.data.items[0].status").value("PLAYING"));
    }

    @Test
    void filtersFinishedRoomsByExplicitStatus() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_W", RelayRoomStatus.WAITING, 1, null, base),
                roomState("ROOM_F", RelayRoomStatus.FINISHED, 4, base.plusMinutes(1), base.plusMinutes(1))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "FINISHED"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.totalElements").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_F"))
            .andExpect(jsonPath("$.data.items[0].status").value("FINISHED"));
    }

    @Test
    void filtersInProgressRoomsByPlayingAndFinalizing() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_W", RelayRoomStatus.WAITING, 1, null, base),
                roomState("ROOM_P", RelayRoomStatus.PLAYING, 4, base.plusMinutes(1), base.plusMinutes(1)),
                roomState("ROOM_Z", RelayRoomStatus.FINALIZING, 4, base.plusMinutes(2), base.plusMinutes(2)),
                roomState("ROOM_F", RelayRoomStatus.FINISHED, 4, base.plusMinutes(3), base.plusMinutes(3))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "IN_PROGRESS"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2))
            .andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_Z"))
            .andExpect(jsonPath("$.data.items[0].status").value("FINALIZING"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("ROOM_P"))
            .andExpect(jsonPath("$.data.items[1].status").value("PLAYING"));
    }

    @Test
    void rejectsClosedStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "CLOSED"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void rejectsInvalidStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("status", "INVALID"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void sortsByCreatedAtDescending() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("OLDEST", RelayRoomStatus.WAITING, 1, null, base.minusMinutes(10)),
                roomState("NEWEST", RelayRoomStatus.WAITING, 1, null, base),
                roomState("MIDDLE", RelayRoomStatus.WAITING, 1, null, base.minusMinutes(5))));

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].roomCode").value("NEWEST"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("MIDDLE"))
            .andExpect(jsonPath("$.data.items[2].roomCode").value("OLDEST"));
    }

    @Test
    void paginatesResults() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 9, 12, 0, 0);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_A", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(0)),
                roomState("ROOM_B", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(1)),
                roomState("ROOM_C", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(2)),
                roomState("ROOM_D", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(3)),
                roomState("ROOM_E", RelayRoomStatus.WAITING, 1, null, base.minusSeconds(4))));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("page", "1").queryParam("size", "2"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2))
            .andExpect(jsonPath("$.data.totalElements").value(5)).andExpect(jsonPath("$.data.page").value(1))
            .andExpect(jsonPath("$.data.size").value(2)).andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_C"))
            .andExpect(jsonPath("$.data.items[1].roomCode").value("ROOM_D"));
    }

    @Test
    void clampsSizeToMaximum() throws Exception {
        given(relayRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "9999")).andExpect(status().isOk()).andExpect(jsonPath("$.data.size").value(100));
    }

    @Test
    void rejectsNegativePage() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("page", "-1")).andExpect(status().isBadRequest());
    }

    @Test
    void rejectsZeroSize() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
            .queryParam("size", "0")).andExpect(status().isBadRequest());
    }

    @Test
    void rejectsUnauthenticatedRequest() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/relay-rooms")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void superAdminGetsActiveRelayRoomList() throws Exception {
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_S", RelayRoomStatus.WAITING, 1, null, LocalDateTime.now())));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_S"));
    }

    @Test
    void viewerGetsActiveRelayRoomList() throws Exception {
        insertAdminUser(VIEWER_ID, VIEWER_LOGIN_ID, VIEWER_NICKNAME, VIEWER_EMAIL, AdminRole.VIEWER);
        given(relayRoomRepository.findAllActiveRooms())
            .willReturn(List.of(roomState("ROOM_V", RelayRoomStatus.WAITING, 1, null, LocalDateTime.now())));

        mockMvc
            .perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(VIEWER_ID, VIEWER_LOGIN_ID, VIEWER_NICKNAME, VIEWER_EMAIL, AdminRole.VIEWER)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("ROOM_V"));
    }

    @Test
    void returnsEmptyListWhenNoActiveRooms() throws Exception {
        given(relayRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(0))
            .andExpect(jsonPath("$.data.totalElements").value(0));
    }

    @ParameterizedTest
    @EnumSource(value = RelayRoomStatus.class, names = {"WAITING", "PLAYING", "FINALIZING", "FINISHED"})
    void adminDeletesActiveRelayRoom(RelayRoomStatus status, CapturedOutput output) throws Exception {
        String roomCode = roomCodeFor(status);
        RelayRoomState roomState = roomState(roomCode, status, 3, LocalDateTime.of(2026, 5, 9, 12, 0),
            LocalDateTime.of(2026, 5, 9, 11, 50));
        given(relayRoomRepository.findByRoomCode(roomCode)).willReturn(Optional.of(roomState));
        given(relayRoomRepository.saveIfUnchanged(eq(roomState), any(RelayRoomState.class))).willReturn(true);

        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", roomCode)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .header("X-Trace-Id", "relay-force-close-" + status.name().toLowerCase())
                .header("X-Forwarded-For", "10.10.70.11, 10.10.70.12"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("릴레이 드로잉 방 삭제 성공"))
            .andExpect(jsonPath("$.data.roomCode").value(roomCode));

        ArgumentCaptor<RelayRoomState> closedRoomCaptor = ArgumentCaptor.forClass(RelayRoomState.class);
        then(relayRoomRepository).should().saveIfUnchanged(eq(roomState), closedRoomCaptor.capture());
        RelayRoomState closedRoomState = closedRoomCaptor.getValue();
        assertThat(closedRoomState.roomCode()).isEqualTo(roomCode);
        assertThat(closedRoomState.status()).isEqualTo(RelayRoomStatus.CLOSED);
        assertThat(closedRoomState.updatedAt()).isNotNull();
        then(relayInviteMetadataSyncService).should().syncWithRoomState(closedRoomState);
        then(relayRoomEventPublisher).should().publishRoomClosed(eq(roomCode), eq(closedRoomState.updatedAt()),
            eq("admin_force"));

        JsonNode auditLog = findAuditLog(output, "relay_room_force_close");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("relay-force-close-" + status.name().toLowerCase());
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("admin");
        assertThat(metadata.path("actor_ip").asText()).isEqualTo("10.10.70.11");
        assertThat(metadata.path("target_type").asText()).isEqualTo("room");
        assertThat(metadata.path("target_id").asText()).isEqualTo(roomCode);
        assertThat(metadata.path("action").asText()).isEqualTo("force_close");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(metadata.path("before").path("status").asText()).isEqualTo(status.name());
        assertThat(metadata.path("after").path("status").asText()).isEqualTo("CLOSED");
    }

    @Test
    void superAdminDeletesActiveRelayRoom() throws Exception {
        String roomCode = "JK7U9V";
        RelayRoomState roomState = roomState(roomCode, RelayRoomStatus.WAITING, 2, null,
            LocalDateTime.of(2026, 5, 9, 12, 0));
        given(relayRoomRepository.findByRoomCode(roomCode)).willReturn(Optional.of(roomState));
        given(relayRoomRepository.saveIfUnchanged(eq(roomState), any(RelayRoomState.class))).willReturn(true);

        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", roomCode).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.roomCode").value(roomCode));
    }

    @Test
    void viewerCannotDeleteActiveRelayRoom() throws Exception {
        insertAdminUser(VIEWER_ID, VIEWER_LOGIN_ID, VIEWER_NICKNAME, VIEWER_EMAIL, AdminRole.VIEWER);

        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", "AB3K9Q").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(VIEWER_ID, VIEWER_LOGIN_ID, VIEWER_NICKNAME, VIEWER_EMAIL, AdminRole.VIEWER)))
            .andExpect(status().isForbidden()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("관리자 작업 권한이 필요합니다."));

        then(relayRoomRepository).should(never()).findByRoomCode(any());
        then(relayRoomRepository).should(never()).saveIfUnchanged(any(), any());
    }

    @Test
    void deletedRoomIsNotReturnedFromActiveRelayRoomList() throws Exception {
        String roomCode = "MN8W2X";
        RelayRoomState roomState = roomState(roomCode, RelayRoomStatus.PLAYING, 2, LocalDateTime.of(2026, 5, 9, 12, 0),
            LocalDateTime.of(2026, 5, 9, 11, 50));
        given(relayRoomRepository.findByRoomCode(roomCode)).willReturn(Optional.of(roomState));
        given(relayRoomRepository.saveIfUnchanged(eq(roomState), any(RelayRoomState.class))).willReturn(true);
        given(relayRoomRepository.findAllActiveRooms()).willReturn(List.of());

        mockMvc.perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", roomCode).header(HttpHeaders.AUTHORIZATION,
            bearerAccessToken())).andExpect(status().isOk());

        mockMvc.perform(get("/api/v1/backoffice/relay-rooms").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(0))
            .andExpect(jsonPath("$.data.totalElements").value(0));
    }

    @Test
    void deleteRejectsInvalidRoomCode() throws Exception {
        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", "not-a-room").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("유효하지 않은 방코드입니다."));

        then(relayRoomRepository).should(never()).findByRoomCode(any());
    }

    @Test
    void deleteRejectsUnauthenticatedRequest() throws Exception {
        mockMvc.perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", "AB3K9Q"))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void deleteReturnsNotFoundWhenRoomDoesNotExist() throws Exception {
        String roomCode = "ZZZZZZ";
        given(relayRoomRepository.findByRoomCode(roomCode)).willReturn(Optional.empty());

        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", roomCode).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("존재하지 않는 방입니다."));
    }

    @Test
    void deleteReturnsConflictWhenRoomAlreadyClosed() throws Exception {
        String roomCode = "PQ4R5S";
        RelayRoomState roomState = roomState(roomCode, RelayRoomStatus.CLOSED, 0, LocalDateTime.of(2026, 5, 9, 12, 0),
            LocalDateTime.of(2026, 5, 9, 12, 10));
        given(relayRoomRepository.findByRoomCode(roomCode)).willReturn(Optional.of(roomState));

        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", roomCode).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("이미 종료된 방입니다."));

        then(relayRoomRepository).should(never()).saveIfUnchanged(any(), any());
    }

    @Test
    void deleteReturnsConflictWhenCasUpdateKeepsFailing() throws Exception {
        String roomCode = "ST6V7W";
        RelayRoomState roomState = roomState(roomCode, RelayRoomStatus.WAITING, 2, null,
            LocalDateTime.of(2026, 5, 9, 12, 0));
        given(relayRoomRepository.findByRoomCode(roomCode)).willReturn(Optional.of(roomState));
        given(relayRoomRepository.saveIfUnchanged(eq(roomState), any(RelayRoomState.class))).willReturn(false);

        mockMvc
            .perform(delete("/api/v1/backoffice/relay-rooms/{roomCode}", roomCode).header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("릴레이 방 상태를 갱신할 수 없습니다."));

        then(relayRoomRepository).should(times(3)).findByRoomCode(roomCode);
        then(relayRoomRepository).should(times(3)).saveIfUnchanged(eq(roomState), any(RelayRoomState.class));
    }

    private RelayRoomState roomState(String roomCode, RelayRoomStatus status, int participantCount,
        LocalDateTime gameStartedAt, LocalDateTime createdAt) {
        List<RelayRoomParticipant> participants = participants(participantCount, createdAt);
        RelayDrawingPart currentPart = status == RelayRoomStatus.PLAYING ? RelayDrawingPart.FACE : null;

        return new RelayRoomState(roomCode, status, "00000000-0000-0000-0000-000000000000", 60, 2, 6, currentPart,
            participants, List.of(), null, null, gameStartedAt, createdAt, createdAt, List.of());
    }

    private List<RelayRoomParticipant> participants(int count, LocalDateTime joinedAt) {
        if (count <= 0) {
            return List.of();
        }

        return java.util.stream.IntStream.range(0, count).mapToObj(
            index -> new RelayRoomParticipant("user-" + index, "닉네임" + index, index == 0, index, true, null, joinedAt))
            .toList();
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", nickname, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private String roomCodeFor(RelayRoomStatus status) {
        return switch (status) {
            case WAITING -> "AB3K9Q";
            case PLAYING -> "CD4M8N";
            case FINALIZING -> "EF5P7R";
            case FINISHED -> "GH6S8T";
            case CLOSED -> "ZZZZZZ";
        };
    }

    private JsonNode findAuditLog(CapturedOutput output, String eventName) throws Exception {
        for (String line : output.getOut().split("\\R")) {
            if (line.contains("\"event_name\":\"%s\"".formatted(eventName))) {
                return objectMapper.readTree(line.substring(line.indexOf('{')));
            }
        }

        throw new AssertionError("Audit log not found. eventName=" + eventName);
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
