package com.nemonicworld.backoffice.setting.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.nullValue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
@ExtendWith(OutputCaptureExtension.class)
class SystemParameterControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "system-parameter-admin";
    private static final String ADMIN_NICKNAME = "System Admin";
    private static final String ADMIN_EMAIL = "system-admin@example.com";
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String SUPER_ADMIN_LOGIN_ID = "system-parameter-super-admin";
    private static final String SUPER_ADMIN_NICKNAME = "Super System Admin";
    private static final String SUPER_ADMIN_EMAIL = "system-super-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS backoffice_setting (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                setting_key VARCHAR(128) NOT NULL UNIQUE,
                setting_value TEXT NOT NULL DEFAULT '{}',
                updated_by BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM backoffice_setting");
        jdbcTemplate.update("DELETE FROM admin_user");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
            AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsSystemParameterList() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", SUPER_ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"value\":200}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.items[0].id").value(11L))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"))
            .andExpect(jsonPath("$.data.items[0].value.value").value(200))
            .andExpect(jsonPath("$.data.items[0].updatedBy.id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.items[0].updatedBy.nickname").value(ADMIN_NICKNAME))
            .andExpect(jsonPath("$.data.items[1].id").value(10L))
            .andExpect(jsonPath("$.data.items[1].key").value("fortune.daily_limit"))
            .andExpect(jsonPath("$.data.items[1].value.value").value(1));
    }

    @Test
    void superAdminGetsSystemParameterList() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", SUPER_ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("fortune.daily_limit"));
    }

    @Test
    void systemParameterListRejectsUnauthenticatedRequest() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);

        mockMvc.perform(get("/api/v1/backoffice/system-parameters")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminGetsEmptySystemParameterList() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(0)).andExpect(jsonPath("$.data.totalElements").value(0));
    }

    @Test
    void adminSearchesSystemParametersByKeyword() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"value\":200}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", "daily"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("fortune.daily_limit"))
            .andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void systemParameterKeywordSearchTreatsLikeWildcardsAsLiteralText() throws Exception {
        insertSetting(10L, "fortune.percent%limit", "{\"value\":1}", ADMIN_ID);
        insertSetting(11L, "community.under_score", "{\"value\":200}", ADMIN_ID);
        insertSetting(12L, "community.plain", "{\"value\":50}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", "%"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("fortune.percent%limit"))
            .andExpect(jsonPath("$.data.totalElements").value(1));

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", "_"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("community.under_score"))
            .andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void blankKeywordReturnsAllSystemParameters() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"value\":200}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", " "))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2))
            .andExpect(jsonPath("$.data.totalElements").value(2));
    }

    @Test
    void adminUpdatesTypedSystemParameters(CapturedOutput output) throws Exception {
        insertSetting(10L, "community.max_memo_count",
            "{\"value\":50,\"unit\":\"count\",\"description\":\"커뮤니티 캔버스 표시 메모 수 제한\"}", SUPER_ADMIN_ID);
        insertSetting(11L, "fortune.daily_limit",
            "{\"value\":1,\"unit\":\"count\",\"description\":\"익명 사용자별 일일 운세 생성 제한\"}", SUPER_ADMIN_ID);
        LocalDateTime before10 = findSettingUpdatedAt(10L);
        LocalDateTime before11 = findSettingUpdatedAt(11L);

        mockMvc
            .perform(patch("/api/v1/backoffice/system-parameters")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).header("X-Trace-Id", "param-change-audit-test")
                .header("X-Real-IP", "10.10.60.11").contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "communityMaxMemoCount": {
                        "value": 200,
                        "unit": "count",
                        "description": "커뮤니티 캔버스 표시 메모 수 제한"
                      },
                      "fortuneDailyLimit": {
                        "value": 5,
                        "unit": "count",
                        "description": "익명 사용자별 일일 운세 생성 제한"
                      }
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.items[0].id").value(10L))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"))
            .andExpect(jsonPath("$.data.items[0].value.value").value(200))
            .andExpect(jsonPath("$.data.items[0].updatedBy.id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.items[1].id").value(11L))
            .andExpect(jsonPath("$.data.items[1].key").value("fortune.daily_limit"))
            .andExpect(jsonPath("$.data.items[1].value.value").value(5))
            .andExpect(jsonPath("$.data.items[1].updatedBy.id").value(ADMIN_ID));

        assertThat(findSettingValue(10L))
            .isEqualTo("{\"value\":200,\"unit\":\"count\",\"description\":\"커뮤니티 캔버스 표시 메모 수 제한\"}");
        assertThat(findSettingValue(11L))
            .isEqualTo("{\"value\":5,\"unit\":\"count\",\"description\":\"익명 사용자별 일일 운세 생성 제한\"}");
        assertThat(findSettingUpdatedBy(10L)).isEqualTo(ADMIN_ID);
        assertThat(findSettingUpdatedBy(11L)).isEqualTo(ADMIN_ID);
        assertThat(findSettingUpdatedAt(10L)).isAfter(before10);
        assertThat(findSettingUpdatedAt(11L)).isAfter(before11);

        JsonNode auditLog = findAuditLog(output, "param_change");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("param-change-audit-test");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("admin");
        assertThat(metadata.path("actor_ip").asText()).isEqualTo("10.10.60.11");
        assertThat(metadata.path("target_type").asText()).isEqualTo("param");
        assertThat(metadata.path("target_id").asText()).isEqualTo("bulk:2");
        assertThat(metadata.path("action").asText()).isEqualTo("update");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(metadata.path("before").path("community.max_memo_count").path("value").asInt()).isEqualTo(50);
        assertThat(metadata.path("after").path("community.max_memo_count").path("value").asInt()).isEqualTo(200);
        assertThat(metadata.path("before").path("fortune.daily_limit").path("value").asInt()).isEqualTo(1);
        assertThat(metadata.path("after").path("fortune.daily_limit").path("value").asInt()).isEqualTo(5);
    }

    @Test
    void superAdminUpdatesTypedSystemParameter() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);

        mockMvc
            .perform(patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN))
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "fortuneDailyLimit": {
                        "value": 99,
                        "unit": "count",
                        "description": "익명 사용자별 일일 운세 생성 제한"
                      }
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items[0].value.value").value(99))
            .andExpect(jsonPath("$.data.items[0].updatedBy.id").value(SUPER_ADMIN_ID));

        assertThat(findSettingUpdatedBy(10L)).isEqualTo(SUPER_ADMIN_ID);
    }

    @Test
    void systemParameterTypedUpdateAcceptsRelayParticipantLimit() throws Exception {
        insertSetting(10L, "relay.room_participant_limit",
            "{\"min\":2,\"max\":6,\"unit\":\"people\",\"description\":\"릴레이 방 참여 인원 제한\"}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "relayRoomParticipantLimit": {
                            "min": 3,
                            "max": 8,
                            "unit": "people",
                            "description": "릴레이 방 참여 인원 제한"
                          }
                        }
                        """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items[0].value.min").value(3))
            .andExpect(jsonPath("$.data.items[0].value.max").value(8));

        assertThat(findSettingValue(10L))
            .isEqualTo("{\"min\":3,\"max\":8,\"unit\":\"people\",\"description\":\"릴레이 방 참여 인원 제한\"}");
    }

    @Test
    void systemParameterTypedUpdateAcceptsRelayRuntimeSettings() throws Exception {
        insertSetting(10L, "relay.room_time_limit_seconds",
            "{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}", ADMIN_ID);
        insertSetting(11L, "relay.reconnect_grace_seconds", "{\"value\":10,\"unit\":\"seconds\"}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "relayRoomTimeLimitSeconds": {
                            "default": 60,
                            "allowed": [45, 60, 90],
                            "unit": "seconds",
                            "description": "릴레이 방 그리기 제한 시간"
                          },
                          "relayReconnectGraceSeconds": {
                            "value": 0,
                            "unit": "seconds",
                            "description": "릴레이 재연결 유예 시간"
                          }
                        }
                        """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(2));

        assertThat(objectMapper.readTree(findSettingValue(10L)).path("default").asInt()).isEqualTo(60);
        assertThat(objectMapper.readTree(findSettingValue(11L)).path("value").asInt()).isZero();
    }

    @Test
    void systemParameterTypedUpdateAcceptsFlipbookRuntimeSettings() throws Exception {
        insertSetting(10L, "flipbook.room_participant_limit", "{\"min\":2,\"max\":6,\"unit\":\"people\"}", ADMIN_ID);
        insertSetting(11L, "flipbook.room_time_limit_seconds",
            "{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}", ADMIN_ID);
        insertSetting(12L, "flipbook.min_frames_per_flipbook", "{\"value\":8,\"unit\":\"frames\"}", ADMIN_ID);
        insertSetting(13L, "flipbook.reconnect_grace_seconds", "{\"value\":10,\"unit\":\"seconds\"}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "flipbookRoomParticipantLimit": {
                            "min": 3,
                            "max": 8,
                            "unit": "people"
                          },
                          "flipbookRoomTimeLimitSeconds": {
                            "default": 60,
                            "allowed": [45, 60, 90],
                            "unit": "seconds"
                          },
                          "flipbookMinFramesPerFlipbook": {
                            "value": 10,
                            "unit": "frames"
                          },
                          "flipbookReconnectGraceSeconds": {
                            "value": 30,
                            "unit": "seconds"
                          }
                        }
                        """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(4));

        assertThat(objectMapper.readTree(findSettingValue(10L)).path("min").asInt()).isEqualTo(3);
        assertThat(objectMapper.readTree(findSettingValue(11L)).path("default").asInt()).isEqualTo(60);
        assertThat(objectMapper.readTree(findSettingValue(12L)).path("value").asInt()).isEqualTo(10);
        assertThat(objectMapper.readTree(findSettingValue(13L)).path("value").asInt()).isEqualTo(30);
    }

    @ParameterizedTest
    @ValueSource(strings = {"{\"min\":1,\"max\":6}", "{\"min\":5,\"max\":4}", "{\"min\":\"2\",\"max\":6}",
        "{\"min\":2}", "{\"min\":2,\"max\":\"6\"}", "{\"min\":2,\"max\":21}", "[2,6]"})
    void systemParameterTypedUpdateRejectsInvalidRelayParticipantLimit(String value) throws Exception {
        insertSetting(10L, "relay.room_participant_limit", "{\"min\":2,\"max\":6}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "relayRoomParticipantLimit": %s
                        }
                        """.formatted(value)))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));

        assertThat(findSettingValue(10L)).isEqualTo("{\"min\":2,\"max\":6}");
    }

    @Test
    void systemParameterTypedUpdateRejectsInvalidFlipbookTimeLimitWithKoreanMessage() throws Exception {
        insertSetting(10L, "flipbook.room_time_limit_seconds",
            "{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "flipbookRoomTimeLimitSeconds": {
                            "default": 60,
                            "allowed": [45, 90],
                            "unit": "seconds"
                          }
                        }
                        """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("플립북 방 제한 시간 설정이 올바르지 않습니다."));

        assertThat(findSettingValue(10L)).isEqualTo("{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}");
    }

    @Test
    void systemParameterTypedUpdateUpdatesOnlyIncludedFields() throws Exception {
        insertSetting(10L, "community.max_memo_count", "{\"value\":50}", ADMIN_ID);
        insertSetting(11L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "communityMaxMemoCount": {
                            "value": 70,
                            "unit": "count",
                            "description": "커뮤니티 캔버스 표시 메모 수 제한"
                          }
                        }
                        """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"));

        assertThat(findSettingValue(10L))
            .isEqualTo("{\"value\":70,\"unit\":\"count\",\"description\":\"커뮤니티 캔버스 표시 메모 수 제한\"}");
        assertThat(findSettingValue(11L)).isEqualTo("{\"value\":1}");
    }

    @Test
    void systemParameterTypedUpdateRejectsEmptyBody() throws Exception {
        mockMvc.perform(patch("/api/v1/backoffice/system-parameters")
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                }
                """)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));
    }

    @ParameterizedTest
    @ValueSource(strings = {"0", "-1", "\"10\""})
    void systemParameterTypedUpdateRejectsInvalidPositiveValue(String value) throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "fortuneDailyLimit": {
                            "value": %s,
                            "unit": "count",
                            "description": "익명 사용자별 일일 운세 생성 제한"
                          }
                        }
                        """.formatted(value)))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));

        assertThat(findSettingValue(10L)).isEqualTo("{\"value\":1}");
    }

    @ParameterizedTest
    @ValueSource(strings = {"{\"default\":45,\"allowed\":[30,60],\"unit\":\"seconds\"}",
        "{\"default\":45,\"allowed\":[],\"unit\":\"seconds\"}", "{\"default\":45,\"unit\":\"seconds\"}",
        "{\"allowed\":[30,45,60],\"unit\":\"seconds\"}",
        "{\"default\":\"45\",\"allowed\":[30,45,60],\"unit\":\"seconds\"}",
        "{\"default\":45,\"allowed\":[30,\"45\",60],\"unit\":\"seconds\"}",
        "{\"default\":4,\"allowed\":[4,45,60],\"unit\":\"seconds\"}",
        "{\"default\":601,\"allowed\":[45,601],\"unit\":\"seconds\"}", "[]"})
    void systemParameterTypedUpdateRejectsInvalidRelayTimeLimit(String value) throws Exception {
        insertSetting(10L, "relay.room_time_limit_seconds",
            "{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "relayRoomTimeLimitSeconds": %s
                        }
                        """.formatted(value)))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));

        assertThat(findSettingValue(10L)).isEqualTo("{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}");
    }

    @ParameterizedTest
    @ValueSource(strings = {"{\"value\":-1,\"unit\":\"seconds\"}", "{\"value\":\"10\",\"unit\":\"seconds\"}",
        "{\"value\":301,\"unit\":\"seconds\"}", "[]"})
    void systemParameterTypedUpdateRejectsInvalidRelayReconnectGrace(String value) throws Exception {
        insertSetting(10L, "relay.reconnect_grace_seconds", "{\"value\":10,\"unit\":\"seconds\"}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "relayReconnectGraceSeconds": %s
                        }
                        """.formatted(value)))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));

        assertThat(findSettingValue(10L)).isEqualTo("{\"value\":10,\"unit\":\"seconds\"}");
    }

    @Test
    void systemParameterTypedUpdateRollsBackWhenRelayRuntimeSettingIsInvalid() throws Exception {
        insertSetting(10L, "relay.room_time_limit_seconds",
            "{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}", ADMIN_ID);
        insertSetting(11L, "relay.reconnect_grace_seconds", "{\"value\":10,\"unit\":\"seconds\"}", ADMIN_ID);

        mockMvc.perform(patch("/api/v1/backoffice/system-parameters")
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "relayRoomTimeLimitSeconds": {
                    "default": 60,
                    "allowed": [45, 60, 90],
                    "unit": "seconds"
                  },
                  "relayReconnectGraceSeconds": {
                    "value": 301,
                    "unit": "seconds"
                  }
                }
                """)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));

        assertThat(findSettingValue(10L)).isEqualTo("{\"default\":45,\"allowed\":[30,45,60],\"unit\":\"seconds\"}");
        assertThat(findSettingValue(11L)).isEqualTo("{\"value\":10,\"unit\":\"seconds\"}");
    }

    @Test
    void systemParameterTypedUpdateRollsBackWhenMappedKeyIsMissing() throws Exception {
        insertSetting(10L, "community.max_memo_count", "{\"value\":50}", ADMIN_ID);

        mockMvc
            .perform(
                patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                    .contentType(MediaType.APPLICATION_JSON).content("""
                        {
                          "communityMaxMemoCount": {
                            "value": 70,
                            "unit": "count",
                            "description": "커뮤니티 캔버스 표시 메모 수 제한"
                          },
                          "fortuneDailyLimit": {
                            "value": 5,
                            "unit": "count",
                            "description": "익명 사용자별 일일 운세 생성 제한"
                          }
                        }
                        """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findSettingValue(10L)).isEqualTo("{\"value\":50}");
    }

    @Test
    void systemParameterTypedUpdateRejectsUnauthenticatedRequest() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);

        mockMvc
            .perform(patch("/api/v1/backoffice/system-parameters").contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "fortuneDailyLimit": {
                    "value": 5,
                    "unit": "count",
                    "description": "익명 사용자별 일일 운세 생성 제한"
                  }
                }
                """)).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findSettingValue(10L)).isEqualTo("{\"value\":1}");
    }

    @Test
    void systemParameterTypedUpdateRejectsInvalidAdminToken() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"value\":1}", ADMIN_ID);

        mockMvc.perform(
            patch("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, "Bearer invalid-token")
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "fortuneDailyLimit": {
                        "value": 5,
                        "unit": "count",
                        "description": "익명 사용자별 일일 운세 생성 제한"
                      }
                    }
                    """))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false));

        assertThat(findSettingValue(10L)).isEqualTo("{\"value\":1}");
    }

    @Test
    void adminGetsSeededSystemParameterWithoutAdminUpdater() throws Exception {
        insertSetting(10L, "community.max_memo_count", "{\"value\":50}", 0L);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"))
            .andExpect(jsonPath("$.data.items[0].updatedBy").value(nullValue()));
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        String roleExpression = isPostgreSql() ? "?::admin_role_type" : "?";
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, %s, NULL, ?, ?, NULL)
            """.formatted(roleExpression), id, loginId, "encoded", nickname, email, role.getValue(),
            Timestamp.valueOf(now), Timestamp.valueOf(now));
    }

    private boolean isPostgreSql() {
        return Boolean.TRUE.equals(jdbcTemplate.execute((ConnectionCallback<Boolean>) connection -> "PostgreSQL"
            .equals(connection.getMetaData().getDatabaseProductName())));
    }

    private void insertSetting(long id, String key, String value, long updatedBy) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO backoffice_setting (
                id,
                setting_key,
                setting_value,
                updated_by,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """, id, key, value, updatedBy, Timestamp.valueOf(now), Timestamp.valueOf(now));
    }

    private String findSettingValue(long id) {
        return jdbcTemplate.queryForObject("SELECT setting_value FROM backoffice_setting WHERE id = ?", String.class,
            id);
    }

    private long findSettingUpdatedBy(long id) {
        Long updatedBy = jdbcTemplate.queryForObject("SELECT updated_by FROM backoffice_setting WHERE id = ?",
            Long.class, id);

        return updatedBy == null ? 0L : updatedBy;
    }

    private LocalDateTime findSettingUpdatedAt(long id) {
        Timestamp timestamp = jdbcTemplate.queryForObject("SELECT updated_at FROM backoffice_setting WHERE id = ?",
            Timestamp.class, id);

        return timestamp == null ? null : timestamp.toLocalDateTime();
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", nickname, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private JsonNode findAuditLog(CapturedOutput output, String eventName) throws Exception {
        for (String line : output.getOut().split("\\R")) {
            if (line.contains("\"event_name\":\"%s\"".formatted(eventName))) {
                return objectMapper.readTree(line);
            }
        }

        throw new AssertionError("Audit log not found. eventName=" + eventName);
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
