package com.nemonicworld.backoffice.setting.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.nullValue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.support.IntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
@AutoConfigureMockMvc
@TestPropertySource(properties = "spring.jpa.hibernate.ddl-auto=none")
class SystemParameterControllerIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "system-parameter-admin";
    private static final String ADMIN_NICKNAME = "System Admin";
    private static final String ADMIN_EMAIL = "system-admin@example.com";
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String SUPER_ADMIN_LOGIN_ID = "system-parameter-super-admin";
    private static final String SUPER_ADMIN_NICKNAME = "Super System Admin";
    private static final String SUPER_ADMIN_EMAIL = "system-super-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS backoffice_setting (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                setting_key VARCHAR(128) NOT NULL UNIQUE,
                setting_value TEXT NOT NULL DEFAULT '{}',
                updated_by BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM backoffice_setting");
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        jdbcTemplate.execute("ALTER TABLE backoffice_setting ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
            AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsSystemParameterList() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"enabled\":true,\"max\":1}", SUPER_ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"max\":200}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.items[0].id").value(11L))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"))
            .andExpect(jsonPath("$.data.items[0].value.max").value(200))
            .andExpect(jsonPath("$.data.items[0].updatedBy.id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.items[0].updatedBy.nickname").value(ADMIN_NICKNAME))
            .andExpect(jsonPath("$.data.items[1].id").value(10L))
            .andExpect(jsonPath("$.data.items[1].key").value("fortune.daily_limit"))
            .andExpect(jsonPath("$.data.items[1].value.enabled").value(true))
            .andExpect(jsonPath("$.data.items[1].value.max").value(1));
    }

    @Test
    void superAdminGetsSystemParameterList() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", SUPER_ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("fortune.daily_limit"));
    }

    @Test
    void systemParameterListRejectsUnauthenticatedRequest() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);

        mockMvc.perform(get("/api/v1/backoffice/system-parameters")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").isNotEmpty());
    }

    @Test
    void adminGetsEmptySystemParameterList() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(0)).andExpect(jsonPath("$.data.totalElements").value(0));
    }

    @Test
    void adminSearchesSystemParametersByKeyword() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"max\":200}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", "daily"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("fortune.daily_limit"))
            .andExpect(jsonPath("$.data.totalElements").value(1));
    }

    @Test
    void blankKeywordReturnsAllSystemParameters() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"max\":200}", ADMIN_ID);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .queryParam("keyword", " "))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2))
            .andExpect(jsonPath("$.data.totalElements").value(2));
    }

    @Test
    void adminBulkUpdatesSystemParameters() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", SUPER_ADMIN_ID);
        insertSetting(11L, "community.max_memo_count", "{\"max\":50}", SUPER_ADMIN_ID);
        LocalDateTime before10 = findSettingUpdatedAt(10L);
        LocalDateTime before11 = findSettingUpdatedAt(11L);

        mockMvc
            .perform(put("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "items": [
                        { "id": 10, "value": { "enabled": true, "max": 5 } },
                        { "id": 11, "value": { "max": 200 } }
                      ]
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.items[0].id").value(11L))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"))
            .andExpect(jsonPath("$.data.items[0].value.max").value(200))
            .andExpect(jsonPath("$.data.items[0].updatedBy.id").value(ADMIN_ID))
            .andExpect(jsonPath("$.data.items[1].id").value(10L))
            .andExpect(jsonPath("$.data.items[1].key").value("fortune.daily_limit"))
            .andExpect(jsonPath("$.data.items[1].value.enabled").value(true))
            .andExpect(jsonPath("$.data.items[1].value.max").value(5))
            .andExpect(jsonPath("$.data.items[1].updatedBy.id").value(ADMIN_ID));

        assertThat(findSettingValue(10L)).isEqualTo("{\"enabled\":true,\"max\":5}");
        assertThat(findSettingValue(11L)).isEqualTo("{\"max\":200}");
        assertThat(findSettingUpdatedBy(10L)).isEqualTo(ADMIN_ID);
        assertThat(findSettingUpdatedBy(11L)).isEqualTo(ADMIN_ID);
        assertThat(findSettingUpdatedAt(10L)).isAfter(before10);
        assertThat(findSettingUpdatedAt(11L)).isAfter(before11);
    }

    @Test
    void superAdminBulkUpdatesSystemParameters() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);

        mockMvc
            .perform(put("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN))
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "items": [
                        { "id": 10, "value": { "max": 99 } }
                      ]
                    }
                    """))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.items[0].value.max").value(99))
            .andExpect(jsonPath("$.data.items[0].updatedBy.id").value(SUPER_ADMIN_ID));

        assertThat(findSettingUpdatedBy(10L)).isEqualTo(SUPER_ADMIN_ID);
    }

    @Test
    void systemParameterBulkUpdateRejectsUnauthenticatedRequest() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);

        mockMvc.perform(put("/api/v1/backoffice/system-parameters").contentType(MediaType.APPLICATION_JSON).content("""
            {
              "items": [
                { "id": 10, "value": { "max": 5 } }
              ]
            }
            """)).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findSettingValue(10L)).isEqualTo("{\"max\":1}");
    }

    @Test
    void systemParameterBulkUpdateRollsBackWhenIdMissing() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);

        mockMvc
            .perform(put("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "items": [
                        { "id": 10, "value": { "max": 9 } },
                        { "id": 9999, "value": { "max": 9 } }
                      ]
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findSettingValue(10L)).isEqualTo("{\"max\":1}");
    }

    @Test
    void systemParameterBulkUpdateRejectsEmptyItems() throws Exception {
        mockMvc.perform(put("/api/v1/backoffice/system-parameters")
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "items": []
                }
                """)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void systemParameterBulkUpdateRejectsDuplicateIds() throws Exception {
        insertSetting(10L, "fortune.daily_limit", "{\"max\":1}", ADMIN_ID);

        mockMvc
            .perform(put("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken())
                .contentType(MediaType.APPLICATION_JSON).content("""
                    {
                      "items": [
                        { "id": 10, "value": { "max": 5 } },
                        { "id": 10, "value": { "max": 7 } }
                      ]
                    }
                    """))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").isNotEmpty());

        assertThat(findSettingValue(10L)).isEqualTo("{\"max\":1}");
    }

    @Test
    void systemParameterBulkUpdateAcceptsVariousJsonValueTypes() throws Exception {
        insertSetting(10L, "key.object", "{}", ADMIN_ID);
        insertSetting(11L, "key.number", "{}", ADMIN_ID);
        insertSetting(12L, "key.string", "{}", ADMIN_ID);
        insertSetting(13L, "key.array", "{}", ADMIN_ID);

        mockMvc.perform(put("/api/v1/backoffice/system-parameters")
            .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).contentType(MediaType.APPLICATION_JSON).content("""
                {
                  "items": [
                    { "id": 10, "value": { "nested": { "ok": true } } },
                    { "id": 11, "value": 42 },
                    { "id": 12, "value": "hello" },
                    { "id": 13, "value": [1, 2, 3] }
                  ]
                }
                """)).andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(4));

        assertThat(findSettingValue(10L)).isEqualTo("{\"nested\":{\"ok\":true}}");
        assertThat(findSettingValue(11L)).isEqualTo("42");
        assertThat(findSettingValue(12L)).isEqualTo("\"hello\"");
        assertThat(findSettingValue(13L)).isEqualTo("[1,2,3]");
    }

    @Test
    void adminGetsSeededSystemParameterWithoutAdminUpdater() throws Exception {
        insertSetting(10L, "community.max_memo_count", "{\"max\":50}", 0L);

        mockMvc
            .perform(get("/api/v1/backoffice/system-parameters").header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].key").value("community.max_memo_count"))
            .andExpect(jsonPath("$.data.items[0].updatedBy").value(nullValue()));
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private void insertSetting(long id, String key, String value, long updatedBy) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO backoffice_setting (
                id,
                setting_key,
                setting_value,
                updated_by,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """, id, key, value, updatedBy, Timestamp.valueOf(now), Timestamp.valueOf(now));
    }

    private String findSettingValue(long id) {
        return jdbcTemplate.queryForObject("SELECT setting_value FROM backoffice_setting WHERE id = ?", String.class,
            id);
    }

    private long findSettingUpdatedBy(long id) {
        Long updatedBy = jdbcTemplate.queryForObject("SELECT updated_by FROM backoffice_setting WHERE id = ?",
            Long.class, id);

        return updatedBy == null ? 0L : updatedBy;
    }

    private LocalDateTime findSettingUpdatedAt(long id) {
        Timestamp timestamp = jdbcTemplate.queryForObject("SELECT updated_at FROM backoffice_setting WHERE id = ?",
            Timestamp.class, id);

        return timestamp == null ? null : timestamp.toLocalDateTime();
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", nickname, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
