package com.nemonicworld.backoffice.infinitecanvas.controller;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.then;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nemonicworld.admin.entity.AdminRole;
import com.nemonicworld.admin.entity.AdminUser;
import com.nemonicworld.auth.service.AdminTokenStore;
import com.nemonicworld.auth.service.IssuedAdminRefreshToken;
import com.nemonicworld.auth.service.StoredAdminRefreshToken;
import com.nemonicworld.common.jwt.AdminTokenClaims;
import com.nemonicworld.common.jwt.JwtTokenProvider;
import com.nemonicworld.infinitecanvas.redis.InfiniteCanvasCursor;
import com.nemonicworld.infinitecanvas.redis.InfiniteCanvasLock;
import com.nemonicworld.infinitecanvas.redis.InfiniteCanvasParticipant;
import com.nemonicworld.infinitecanvas.redis.InfiniteCanvasState;
import com.nemonicworld.infinitecanvas.redis.InfiniteCanvasStatus;
import com.nemonicworld.infinitecanvas.repository.InfiniteCanvasActiveCanvasPage;
import com.nemonicworld.infinitecanvas.repository.InfiniteCanvasRepository;
import com.nemonicworld.infinitecanvas.service.support.InfiniteCanvasInviteMetadataSyncService;
import com.nemonicworld.infinitecanvas.websocket.InfiniteCanvasEventPublisher;
import com.nemonicworld.support.AbstractReadOnlyIntegrationTest;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@ExtendWith(OutputCaptureExtension.class)
class BackofficeInfiniteCanvasControllerIntegrationTest extends AbstractReadOnlyIntegrationTest {

    private static final long ADMIN_ID = 1L;
    private static final String ADMIN_LOGIN_ID = "infinite-canvas-admin";
    private static final String ADMIN_NICKNAME = "Canvas Admin";
    private static final String ADMIN_EMAIL = "infinite-canvas-admin@example.com";
    private static final long SUPER_ADMIN_ID = 2L;
    private static final String SUPER_ADMIN_LOGIN_ID = "infinite-canvas-super-admin";
    private static final String SUPER_ADMIN_NICKNAME = "Super Canvas";
    private static final String SUPER_ADMIN_EMAIL = "infinite-canvas-super-admin@example.com";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private InfiniteCanvasRepository infiniteCanvasRepository;

    @MockitoBean
    private InfiniteCanvasInviteMetadataSyncService infiniteCanvasInviteMetadataSyncService;

    @MockitoBean
    private InfiniteCanvasEventPublisher infiniteCanvasEventPublisher;

    @BeforeEach
    void prepareTables() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
        jdbcTemplate.update("DELETE FROM admin_user");
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH 100");
        insertAdminUser(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
        insertAdminUser(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
            AdminRole.SUPER_ADMIN);
    }

    @Test
    void adminGetsActiveInfiniteCanvasList() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 15, 12, 0, 0);
        InfiniteCanvasState oldCanvas = canvasState("AC3K9A", InfiniteCanvasStatus.ACTIVE, 1, 1, 2, 3L,
            base.minusMinutes(10));
        InfiniteCanvasState newCanvas = canvasState("AC3K9B", InfiniteCanvasStatus.ACTIVE, 3, 2, 5, 7L, base);
        InfiniteCanvasState closedCanvas = canvasState("AC3K9C", InfiniteCanvasStatus.CLOSED, 2, 0, 1, 8L,
            base.plusMinutes(1));
        given(infiniteCanvasRepository.findActiveCanvases(0, 20))
            .willReturn(new InfiniteCanvasActiveCanvasPage(List.of(newCanvas, oldCanvas), 2));

        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken()))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("활성 무한 캔버스 목록 조회 성공"))
            .andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.totalElements").value(2))
            .andExpect(jsonPath("$.data.page").value(0)).andExpect(jsonPath("$.data.size").value(20))
            .andExpect(jsonPath("$.data.items[0].roomCode").value(newCanvas.roomCode()))
            .andExpect(jsonPath("$.data.items[0].inviteCode").doesNotExist())
            .andExpect(jsonPath("$.data.items[0].status").value("ACTIVE"))
            .andExpect(jsonPath("$.data.items[0].participantCount").value(3))
            .andExpect(jsonPath("$.data.items[0].maxParticipants").value(6))
            .andExpect(jsonPath("$.data.items[0].connectedParticipantCount").value(2))
            .andExpect(jsonPath("$.data.items[0].elementCount").value(5))
            .andExpect(jsonPath("$.data.items[0].revision").value(7))
            .andExpect(jsonPath("$.data.items[1].roomCode").value(oldCanvas.roomCode()));
    }

    @Test
    void filtersByActiveStatus() throws Exception {
        InfiniteCanvasState canvas = canvasState("AC3K9D", InfiniteCanvasStatus.ACTIVE, 1, 1, 0, 0L,
            LocalDateTime.of(2026, 5, 15, 12, 0, 0));
        given(infiniteCanvasRepository.findActiveCanvases(0, 20))
            .willReturn(new InfiniteCanvasActiveCanvasPage(List.of(canvas), 1));

        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("status", "ACTIVE"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value(canvas.roomCode()));
    }

    @Test
    void rejectsClosedOrInvalidStatusFilter() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("status", "CLOSED"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("조회할 수 없는 무한 캔버스 상태입니다."));

        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("status", "INVALID"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("조회할 수 없는 무한 캔버스 상태입니다."));
    }

    @Test
    void paginatesResultsAndClampsSize() throws Exception {
        LocalDateTime base = LocalDateTime.of(2026, 5, 15, 12, 0, 0);
        given(infiniteCanvasRepository.findActiveCanvases(1, 2)).willReturn(new InfiniteCanvasActiveCanvasPage(
            List.of(canvasState("AC3K9C", InfiniteCanvasStatus.ACTIVE, 1, 1, 0, 0L, base.minusSeconds(2))), 3));
        given(infiniteCanvasRepository.findActiveCanvases(0, 100)).willReturn(new InfiniteCanvasActiveCanvasPage(
            List.of(canvasState("AC3K9A", InfiniteCanvasStatus.ACTIVE, 1, 1, 0, 0L, base)), 3));

        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("page", "1").queryParam("size", "2"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.totalElements").value(3)).andExpect(jsonPath("$.data.page").value(1))
            .andExpect(jsonPath("$.data.size").value(2))
            .andExpect(jsonPath("$.data.items[0].roomCode").value("AC3K9C"));

        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("size", "9999"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.size").value(100));
    }

    @Test
    void rejectsInvalidPageAndSize() throws Exception {
        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("page", "-1"))
            .andExpect(status().isBadRequest());
        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("size", "0"))
            .andExpect(status().isBadRequest());
        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("page", "abc"))
            .andExpect(status().isBadRequest());
        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).queryParam("size", "abc"))
            .andExpect(status().isBadRequest());
    }

    @Test
    void rejectsUnauthenticatedListRequest() throws Exception {
        mockMvc.perform(get("/api/v1/backoffice/infinite-canvas/canvases")).andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void superAdminGetsActiveInfiniteCanvasList() throws Exception {
        InfiniteCanvasState canvas = canvasState("AC3K9E", InfiniteCanvasStatus.ACTIVE, 1, 1, 0, 0L,
            LocalDateTime.of(2026, 5, 15, 12, 0, 0));
        given(infiniteCanvasRepository.findActiveCanvases(0, 20))
            .willReturn(new InfiniteCanvasActiveCanvasPage(List.of(canvas), 1));

        mockMvc
            .perform(get("/api/v1/backoffice/infinite-canvas/canvases").header(HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(1))
            .andExpect(jsonPath("$.data.items[0].roomCode").value(canvas.roomCode()));
    }

    @Test
    void adminClosesActiveInfiniteCanvas(CapturedOutput output) throws Exception {
        String roomCode = "AC3K9F";
        InfiniteCanvasState state = canvasState(roomCode, InfiniteCanvasStatus.ACTIVE, 3, 2, 4, 9L,
            LocalDateTime.of(2026, 5, 15, 12, 0, 0), true);
        given(infiniteCanvasRepository.findByRoomCode(roomCode)).willReturn(Optional.of(state));
        given(infiniteCanvasRepository.saveIfUnchanged(eq(state), any(InfiniteCanvasState.class))).willReturn(true);

        mockMvc
            .perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", roomCode)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()).header("X-Trace-Id", "canvas-force-close")
                .header("X-Real-IP", "10.10.80.12"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.message").value("무한 캔버스 강제 종료 성공"))
            .andExpect(jsonPath("$.data.roomCode").value(roomCode));

        ArgumentCaptor<InfiniteCanvasState> closedStateCaptor = ArgumentCaptor.forClass(InfiniteCanvasState.class);
        then(infiniteCanvasRepository).should().saveIfUnchanged(eq(state), closedStateCaptor.capture());
        InfiniteCanvasState closedState = closedStateCaptor.getValue();
        assertThat(closedState.roomCode()).isEqualTo(roomCode);
        assertThat(closedState.status()).isEqualTo(InfiniteCanvasStatus.CLOSED);
        assertThat(closedState.closedAt()).isNotNull();
        assertThat(closedState.updatedAt()).isEqualTo(closedState.closedAt());
        assertThat(closedState.participants()).isEqualTo(state.participants());
        assertThat(closedState.elements()).isEqualTo(state.elements());
        assertThat(closedState.locks()).isEmpty();
        assertThat(closedState.cursors()).isEmpty();
        then(infiniteCanvasInviteMetadataSyncService).should().syncWithCanvasState(closedState);
        then(infiniteCanvasEventPublisher).should().publishCanvasClosed(eq(roomCode), eq(closedState.closedAt()));

        JsonNode canvasClosedLog = findLog(output, "infinite_canvas_closed");
        JsonNode canvasClosedMetadata = canvasClosedLog.path("metadata");
        assertThat(canvasClosedMetadata.path("room_code").asText()).isEqualTo(roomCode);
        assertThat(canvasClosedMetadata.path("close_reason").asText()).isEqualTo("admin_force");
        assertThat(canvasClosedMetadata.path("canvas_status_before").asText()).isEqualTo("ACTIVE");
        assertThat(canvasClosedMetadata.path("participant_count").asInt()).isEqualTo(3);

        JsonNode auditLog = findLog(output, "infinite_canvas_force_close");
        JsonNode metadata = auditLog.path("metadata");
        assertThat(auditLog.path("service").asText()).isEqualTo("backoffice-api");
        assertThat(auditLog.path("trace_id").asText()).isEqualTo("canvas-force-close");
        assertThat(metadata.path("actor_id").asText()).isEqualTo(String.valueOf(ADMIN_ID));
        assertThat(metadata.path("actor_role").asText()).isEqualTo("admin");
        assertThat(metadata.path("actor_ip").asText()).isEqualTo("10.10.80.12");
        assertThat(metadata.path("target_type").asText()).isEqualTo("room");
        assertThat(metadata.path("target_id").asText()).isEqualTo(roomCode);
        assertThat(metadata.path("action").asText()).isEqualTo("force_close");
        assertThat(metadata.path("result").asText()).isEqualTo("success");
        assertThat(metadata.path("before").path("status").asText()).isEqualTo("ACTIVE");
        assertThat(metadata.path("after").path("status").asText()).isEqualTo("CLOSED");
    }

    @Test
    void superAdminClosesActiveInfiniteCanvas() throws Exception {
        String roomCode = "AC3K9G";
        InfiniteCanvasState state = canvasState(roomCode, InfiniteCanvasStatus.ACTIVE, 1, 1, 0, 0L,
            LocalDateTime.of(2026, 5, 15, 12, 0, 0));
        given(infiniteCanvasRepository.findByRoomCode(roomCode)).willReturn(Optional.of(state));
        given(infiniteCanvasRepository.saveIfUnchanged(eq(state), any(InfiniteCanvasState.class))).willReturn(true);

        mockMvc
            .perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", roomCode).header(
                HttpHeaders.AUTHORIZATION,
                bearerAccessToken(SUPER_ADMIN_ID, SUPER_ADMIN_LOGIN_ID, SUPER_ADMIN_NICKNAME, SUPER_ADMIN_EMAIL,
                    AdminRole.SUPER_ADMIN)))
            .andExpect(status().isOk()).andExpect(jsonPath("$.data.roomCode").value(roomCode));
    }

    @Test
    void rejectsInvalidRoomCodeOnClose() throws Exception {
        mockMvc
            .perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", "not-a-uuid")
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("유효하지 않은 방코드입니다."));

        then(infiniteCanvasRepository).should(never()).findByRoomCode(any());
        then(infiniteCanvasRepository).should(never()).saveIfUnchanged(any(), any());
    }

    @Test
    void rejectsUnauthenticatedCloseRequest() throws Exception {
        mockMvc.perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", "AC3K9H"))
            .andExpect(status().isUnauthorized()).andExpect(jsonPath("$.success").value(false));
    }

    @Test
    void closeReturnsNotFoundWhenCanvasDoesNotExist() throws Exception {
        String roomCode = "AC3K9J";
        given(infiniteCanvasRepository.findByRoomCode(roomCode)).willReturn(Optional.empty());

        mockMvc
            .perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", roomCode)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isNotFound()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("활성 무한 캔버스를 찾을 수 없습니다."));

        then(infiniteCanvasRepository).should(never()).saveIfUnchanged(any(), any());
        then(infiniteCanvasEventPublisher).should(never()).publishCanvasClosed(any(), any());
    }

    @Test
    void closeClosedCanvasReturnsConflict() throws Exception {
        String roomCode = "AC3K9K";
        InfiniteCanvasState state = canvasState(roomCode, InfiniteCanvasStatus.CLOSED, 1, 0, 0, 0L,
            LocalDateTime.of(2026, 5, 15, 12, 0, 0));
        given(infiniteCanvasRepository.findByRoomCode(roomCode)).willReturn(Optional.of(state));

        mockMvc
            .perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", roomCode)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("이미 종료된 캔버스입니다."));

        then(infiniteCanvasRepository).should(never()).saveIfUnchanged(any(), any());
        then(infiniteCanvasEventPublisher).should(never()).publishCanvasClosed(any(), any());
    }

    @Test
    void closeReturnsConflictWhenCasRetryFails() throws Exception {
        String roomCode = "AC3K9M";
        InfiniteCanvasState state = canvasState(roomCode, InfiniteCanvasStatus.ACTIVE, 1, 1, 0, 0L,
            LocalDateTime.of(2026, 5, 15, 12, 0, 0));
        given(infiniteCanvasRepository.findByRoomCode(roomCode)).willReturn(Optional.of(state));
        given(infiniteCanvasRepository.saveIfUnchanged(eq(state), any(InfiniteCanvasState.class))).willReturn(false);

        mockMvc
            .perform(delete("/api/v1/backoffice/infinite-canvas/canvases/{roomCode}", roomCode)
                .header(HttpHeaders.AUTHORIZATION, bearerAccessToken()))
            .andExpect(status().isConflict()).andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("무한 캔버스 상태 갱신 충돌이 발생했습니다. 다시 시도해주세요."));

        then(infiniteCanvasRepository).should(times(8)).saveIfUnchanged(eq(state), any(InfiniteCanvasState.class));
        then(infiniteCanvasEventPublisher).should(never()).publishCanvasClosed(any(), any());
    }

    private InfiniteCanvasState canvasState(String roomCode, InfiniteCanvasStatus status, int participantCount,
        int connectedCount, int elementCount, long revision, LocalDateTime createdAt) {
        return canvasState(roomCode, status, participantCount, connectedCount, elementCount, revision, createdAt,
            false);
    }

    private InfiniteCanvasState canvasState(String roomCode, InfiniteCanvasStatus status, int participantCount,
        int connectedCount, int elementCount, long revision, LocalDateTime createdAt, boolean withRealtimeState) {
        List<InfiniteCanvasParticipant> participants = participants(participantCount, connectedCount, createdAt);
        List<JsonNode> elements = java.util.stream.IntStream.range(0, elementCount)
            .mapToObj(index -> objectMapper.createObjectNode().put("id", "element-" + index).put("type", "shape"))
            .map(JsonNode.class::cast).toList();
        Map<String, InfiniteCanvasLock> locks = withRealtimeState
            ? Map.of("element-0",
                new InfiniteCanvasLock("element-0", participants.getFirst().userUuid(), createdAt,
                    createdAt.plusSeconds(30)))
            : Map.of();
        Map<String, InfiniteCanvasCursor> cursors = withRealtimeState
            ? Map.of(participants.getFirst().userUuid(),
                new InfiniteCanvasCursor(participants.getFirst().userUuid(), 1.0, 2.0, 1.0, null, createdAt))
            : Map.of();

        return new InfiniteCanvasState(roomCode, status, participants.getFirst().userUuid(), participants, elements,
            List.of(), locks, cursors, objectMapper.createObjectNode().put("x", 0).put("y", 0).put("zoom", 1), 6,
            revision, createdAt, createdAt, status == InfiniteCanvasStatus.CLOSED ? createdAt : null);
    }

    private List<InfiniteCanvasParticipant> participants(int count, int connectedCount, LocalDateTime joinedAt) {
        return java.util.stream.IntStream.range(0, count)
            .mapToObj(index -> new InfiniteCanvasParticipant(UUID.randomUUID().toString(), "참여자" + index, "#72DDF7",
                null, index == 0, index < connectedCount, joinedAt, index < connectedCount ? joinedAt : null, joinedAt))
            .toList();
    }

    private void insertAdminUser(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
            """, id, loginId, "encoded", nickname, email, role.getValue(), Timestamp.valueOf(now),
            Timestamp.valueOf(now));
    }

    private String bearerAccessToken() {
        return bearerAccessToken(ADMIN_ID, ADMIN_LOGIN_ID, ADMIN_NICKNAME, ADMIN_EMAIL, AdminRole.ADMIN);
    }

    private String bearerAccessToken(long id, String loginId, String nickname, String email, AdminRole role) {
        LocalDateTime now = LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS);
        AdminUser adminUser = new AdminUser(id, loginId, "encoded", nickname, email, role, null, now, now, null);

        return "Bearer %s".formatted(jwtTokenProvider.createAccessToken(adminUser).accessToken());
    }

    private JsonNode findLog(CapturedOutput output, String eventName) throws Exception {
        for (String line : output.getOut().split("\\R")) {
            if (line.contains("\"event_name\":\"%s\"".formatted(eventName))) {
                return objectMapper.readTree(line.substring(line.indexOf('{')));
            }
        }

        throw new AssertionError("Log not found. eventName=" + eventName);
    }

    @TestConfiguration
    static class AdminTokenStoreTestConfig {

        @Bean
        @Primary
        AdminTokenStore adminTokenStore() {
            return new NoOpAdminTokenStore();
        }
    }

    static class NoOpAdminTokenStore implements AdminTokenStore {

        @Override
        public IssuedAdminRefreshToken issueRefreshToken(AdminUser adminUser) {
            Instant expiresAt = Instant.now().plusSeconds(60);

            return new IssuedAdminRefreshToken("unused", OffsetDateTime.ofInstant(expiresAt, ZoneOffset.UTC));
        }

        @Override
        public Optional<StoredAdminRefreshToken> findRefreshToken(String refreshToken) {
            return Optional.empty();
        }

        @Override
        public void revokeRefreshToken(String refreshToken) {
        }

        @Override
        public void revokeAllRefreshTokens(Long adminId) {
        }

        @Override
        public void blacklistAccessToken(AdminTokenClaims claims) {
        }

        @Override
        public void revokeAccessTokensIssuedBefore(Long adminId, Instant revokedAt) {
        }

        @Override
        public boolean isAccessTokenRevoked(AdminTokenClaims claims) {
            return false;
        }
    }
}
