package com.nemonicworld.support;

import com.nemonicworld.admin.entity.AdminRole;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;

public class AdminUserTestFixture {

    private static final String ENCODED_PASSWORD = "encoded";

    private final JdbcTemplate jdbcTemplate;
    private final PasswordEncoder passwordEncoder;

    public AdminUserTestFixture(JdbcTemplate jdbcTemplate) {
        this(jdbcTemplate, null);
    }

    public AdminUserTestFixture(JdbcTemplate jdbcTemplate, PasswordEncoder passwordEncoder) {
        this.jdbcTemplate = jdbcTemplate;
        this.passwordEncoder = passwordEncoder;
    }

    public void reset(long nextId) {
        ensureTable();
        deleteAll();
        restartIdentity(nextId);
    }

    public void deleteAll() {
        jdbcTemplate.update("DELETE FROM admin_user");
    }

    public void ensureTable() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS admin_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login_id VARCHAR(64) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                nickname VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                role VARCHAR(32) NOT NULL,
                last_login_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL
            )
            """);
    }

    public void restartIdentity(long nextId) {
        jdbcTemplate.execute("ALTER TABLE admin_user ALTER COLUMN id RESTART WITH " + nextId);
    }

    public void insertEncoded(long id, String loginId, String nickname, String email, AdminRole role) {
        insert(id, loginId, ENCODED_PASSWORD, nickname, email, role.getValue(), null);
    }

    public void insertRawPassword(long id, String loginId, String rawPassword, String nickname, String email,
        String role, LocalDateTime deletedAt) {
        if (passwordEncoder == null) {
            throw new IllegalStateException("PasswordEncoder is required to insert raw admin passwords.");
        }

        insert(id, loginId, passwordEncoder.encode(rawPassword), nickname, email, role, deletedAt);
    }

    private void insert(long id, String loginId, String passwordHash, String nickname, String email, String role,
        LocalDateTime deletedAt) {
        LocalDateTime now = LocalDateTime.now().minusDays(1).truncatedTo(ChronoUnit.SECONDS);
        String roleExpression = isPostgreSql() ? "?::admin_role_type" : "?";
        jdbcTemplate.update("""
            INSERT INTO admin_user (
                id,
                login_id,
                password_hash,
                nickname,
                email,
                role,
                last_login_at,
                created_at,
                updated_at,
                deleted_at
            )
            VALUES (?, ?, ?, ?, ?, %s, NULL, ?, ?, ?)
            """.formatted(roleExpression), id, loginId, passwordHash, nickname, email, role, Timestamp.valueOf(now),
            Timestamp.valueOf(now), deletedAt == null ? null : Timestamp.valueOf(deletedAt));
    }

    private boolean isPostgreSql() {
        return Boolean.TRUE.equals(jdbcTemplate.execute((ConnectionCallback<Boolean>) connection -> "PostgreSQL"
            .equals(connection.getMetaData().getDatabaseProductName())));
    }
}
