package com.nemonicworld.support;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;

public class CsInquiryTestFixture {

    private final JdbcTemplate jdbcTemplate;

    public CsInquiryTestFixture(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void reset(long nextId) {
        ensureTable();
        deleteAll();
        restartIdentity(nextId);
    }

    public void ensureTable() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS cs_inquiry (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL,
                inquiry_type VARCHAR(32) NOT NULL,
                title VARCHAR(255) NOT NULL,
                content VARCHAR(1000) NULL,
                email VARCHAR(255) NULL,
                attachments TEXT NULL,
                meta TEXT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'new',
                assigned_to BIGINT NULL,
                response_note TEXT NULL,
                responded_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
    }

    public void deleteAll() {
        jdbcTemplate.update("DELETE FROM cs_inquiry");
    }

    public void restartIdentity(long nextId) {
        jdbcTemplate.execute("ALTER TABLE cs_inquiry ALTER COLUMN id RESTART WITH " + nextId);
    }

    public void insert(long id, UUID userUuid, String type, String title, String content, String email,
        String attachments, String meta, String status, Long assignedTo, String responseNote, LocalDateTime respondedAt,
        LocalDateTime createdAt, LocalDateTime updatedAt) {
        jdbcTemplate.update("""
            INSERT INTO cs_inquiry (
                id,
                user_id,
                inquiry_type,
                title,
                content,
                email,
                attachments,
                meta,
                status,
                assigned_to,
                response_note,
                responded_at,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, id, userUuid, type, title, content, email, attachments, meta, status, assignedTo, responseNote,
            respondedAt == null ? null : Timestamp.valueOf(respondedAt), Timestamp.valueOf(createdAt),
            Timestamp.valueOf(updatedAt));
    }
}
