package com.nemonicworld.support;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import org.springframework.jdbc.core.JdbcTemplate;

public class GmsPromptTestFixture {

    private final JdbcTemplate jdbcTemplate;

    public GmsPromptTestFixture(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void resetPromptTables() {
        ensurePromptTables();
        deletePromptRows();
    }

    public void dropPromptTables() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS gms_prompt_feature_state");
        jdbcTemplate.execute("DROP TABLE IF EXISTS gms_prompt_template");
    }

    public void ensurePromptTables() {
        ensurePromptTemplateTable();
        ensurePromptFeatureStateTable();
    }

    public void ensurePromptTemplateTable() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS gms_prompt_template (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                prompt_name VARCHAR(64) NOT NULL UNIQUE,
                template_text TEXT NOT NULL,
                feature_type VARCHAR(32) NOT NULL,
                created_by BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                deleted_at TIMESTAMP NULL,
                is_active BOOLEAN NOT NULL DEFAULT FALSE,
                activated_at TIMESTAMP NULL,
                activated_by BIGINT NULL
            )
            """);
    }

    public void ensurePromptFeatureStateTable() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS gms_prompt_feature_state (
                feature_type VARCHAR(32) PRIMARY KEY,
                current_prompt_id BIGINT NULL,
                updated_by BIGINT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """);
    }

    public void deletePromptRows() {
        jdbcTemplate.update("DELETE FROM gms_prompt_feature_state");
        jdbcTemplate.update("DELETE FROM gms_prompt_template");
    }

    public void insertPromptTemplate(long id, String name, String content, String featureType, long createdBy,
        LocalDateTime timestamp, LocalDateTime deletedAt) {
        insertPromptTemplate(id, name, content, featureType, createdBy, timestamp, deletedAt, false, null);
    }

    public void insertActivePromptTemplate(long id, String name, String content, String featureType, long createdBy,
        LocalDateTime timestamp, LocalDateTime deletedAt, long activatedBy) {
        insertPromptTemplate(id, name, content, featureType, createdBy, timestamp, deletedAt, true, activatedBy);
        upsertPromptFeatureState(featureType, id, activatedBy, timestamp);
    }

    private void insertPromptTemplate(long id, String name, String content, String featureType, long createdBy,
        LocalDateTime timestamp, LocalDateTime deletedAt, boolean active, Long activatedBy) {
        jdbcTemplate.update("""
            INSERT INTO gms_prompt_template (
                id,
                prompt_name,
                template_text,
                feature_type,
                created_by,
                created_at,
                updated_at,
                deleted_at,
                is_active,
                activated_at,
                activated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, id, name, content, featureType, createdBy, Timestamp.valueOf(timestamp), Timestamp.valueOf(timestamp),
            deletedAt == null ? null : Timestamp.valueOf(deletedAt), active,
            active ? Timestamp.valueOf(timestamp) : null, activatedBy);
    }

    public void upsertPromptFeatureState(String featureType, long currentPromptId, long updatedBy,
        LocalDateTime timestamp) {
        jdbcTemplate.update("""
            MERGE INTO gms_prompt_feature_state (
                feature_type,
                current_prompt_id,
                updated_by,
                created_at,
                updated_at
            )
            KEY (feature_type)
            VALUES (?, ?, ?, ?, ?)
            """, featureType, currentPromptId, updatedBy, Timestamp.valueOf(timestamp), Timestamp.valueOf(timestamp));
    }
}
